import { access, chmod, mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { loadManifest, runDiff, runSync } from "../src/index.js";
import type { ManifestFile, ReconcileResult } from "../src/index.js";

async function createWorkspace(prefix: string): Promise<string> {
  return mkdtemp(path.join(os.tmpdir(), prefix));
}

async function exists(rootDir: string, relativePath: string): Promise<boolean> {
  try {
    await access(path.join(rootDir, relativePath));
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return false;
    }

    throw error;
  }
}

async function readJson(rootDir: string, relativePath: string): Promise<Record<string, unknown>> {
  return JSON.parse(await readText(rootDir, relativePath)) as Record<string, unknown>;
}

async function readText(rootDir: string, relativePath: string): Promise<string> {
  return readFile(path.join(rootDir, relativePath), "utf8");
}

async function writeText(rootDir: string, relativePath: string, content: string): Promise<void> {
  const filePath = path.join(rootDir, relativePath);
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf8");
}

function asObject(value: unknown): Record<string, unknown> {
  expect(value).toBeTypeOf("object");
  expect(value).not.toBeNull();
  expect(Array.isArray(value)).toBe(false);
  return value as Record<string, unknown>;
}

function asArray(value: unknown): unknown[] {
  expect(Array.isArray(value)).toBe(true);
  return value as unknown[];
}

function changedPaths(result: ReconcileResult): string[] {
  return [...result.added, ...result.modified, ...result.removed].map((entry) => entry.path).sort((left, right) => left.localeCompare(right));
}

function manifestPaths(manifest: ManifestFile): string[] {
  return manifest.files.map((entry) => entry.path).sort((left, right) => left.localeCompare(right));
}

describe("autonomous execution M0 contracts", () => {
  it("locks the Codex-only sync, diff, MCP, context visibility, and manifest contract", async () => {
    const rootDir = await createWorkspace("harness-autonomous-codex-");
    await writeText(rootDir, "AGENTS.md.template", "# Codex autonomous fixture\n");
    await writeText(rootDir, ".codex/config.toml.template", 'inherit = "core"\n');
    await writeText(
      rootDir,
      "harness.yaml",
      `
name: autonomous-codex-only
tools:
  - codex
canonical:
  instructions: ./AGENTS.md.template
  codexConfig: ./.codex/config.toml.template
context:
  no_active_context:
    - path: docs/archive/
      reason: Historical run output.
    - path: docs/research/**
      mode: soft_ignore
mcp:
  servers:
    beta:
      command: node
      args: ["beta.js"]
      env: {}
    alpha:
      command: npx
      args: ["-y", "@modelcontextprotocol/server-filesystem"]
      env:
        A_TOKEN: "\${A_TOKEN}"
adapters:
  codex:
    target: .
`
    );

    const initialDiff = await runDiff(rootDir);
    expect(initialDiff.added.map((entry) => entry.path).sort((left, right) => left.localeCompare(right))).toEqual([
      ".codex/config.toml",
      "AGENTS.md"
    ]);

    const syncResult = await runSync(rootDir);
    expect(syncResult.added.map((entry) => entry.path).sort((left, right) => left.localeCompare(right))).toEqual([
      ".codex/config.toml",
      "AGENTS.md"
    ]);

    const agents = await readText(rootDir, "AGENTS.md");
    const codexConfig = await readText(rootDir, ".codex/config.toml");
    const manifest = await loadManifest(rootDir);
    const afterSyncDiff = await runDiff(rootDir);

    expect(agents).toContain("<!-- generated by harness; do not edit -->");
    expect(agents).toContain("# Codex autonomous fixture");
    expect(codexConfig).toContain('inherit = "core"');
    expect(codexConfig).toContain('default_permissions = "harness-no-active-context"');
    expect(codexConfig).toContain("[permissions.harness-no-active-context.filesystem]");
    expect(codexConfig).toContain('"docs/archive" = "none"');
    expect(codexConfig).toContain('"docs/archive/**" = "none"');
    expect(codexConfig).not.toContain("docs/research");
    expect(codexConfig.indexOf("[mcp_servers.alpha]")).toBeLessThan(codexConfig.indexOf("[mcp_servers.beta]"));
    expect(codexConfig).toContain('args = [ "-y", "@modelcontextprotocol/server-filesystem" ]');
    expect(codexConfig).toContain('env = { A_TOKEN = "${A_TOKEN}" }');
    expect(manifestPaths(manifest)).toEqual([".codex/config.toml", "AGENTS.md"]);
    expect(changedPaths(afterSyncDiff)).toEqual([]);
    expect(afterSyncDiff.unchanged.map((entry) => entry.path).sort((left, right) => left.localeCompare(right))).toEqual(manifestPaths(manifest));
  });

  it("locks the Claude+Codex projection contract for context visibility, hooks, plugins, MCP, and runtime metric filtering", async () => {
    const rootDir = await createWorkspace("harness-autonomous-multi-tool-");
    await mkdir(path.join(rootDir, ".git"), { recursive: true });
    await writeText(rootDir, "AGENTS.md.template", "# Multi-tool autonomous fixture\n");
    await writeText(rootDir, ".codex/config.toml.template", 'profile = "project"\n');
    await writeText(rootDir, "agents/reviewer.md", "---\ndescription: Review code\n---\nReview generated work.\n");
    await writeText(rootDir, "commands/review.md", "Run the review workflow.\n");
    await writeText(rootDir, "docs/README.md", "# Active docs\n");
    await writeText(rootDir, "docs/archive/old.md", "# Archived run\n");
    await writeText(rootDir, "rules/style.md", "Follow the style guide.\n");
    await writeText(rootDir, "scripts/check.sh", "#!/usr/bin/env bash\necho check\n");
    await chmod(path.join(rootDir, "scripts/check.sh"), 0o755);
    await writeText(rootDir, "skills/atom-example/SKILL.md", "---\nname: atom-example\n---\n# Atom example\n");
    await writeText(rootDir, "metrics/events.schema.md", "# Events schema\n");
    await writeText(rootDir, "metrics/events.jsonl", '{"kind":"runtime"}\n');
    await writeText(
      rootDir,
      "harness.yaml",
      `
name: autonomous-multi-tool
tools:
  - claude-code
  - codex
canonical:
  instructions: ./AGENTS.md.template
  codexConfig: ./.codex/config.toml.template
projects:
  references:
    machpro:
      path: ../machpro
      description: MachPro reference
context:
  no_active_context:
    - path: docs/archive/
      reason: Archived experiments should not be loaded by default.
mcp:
  servers:
    beta:
      command: node
      args: ["beta.js"]
      env: {}
    alpha:
      command: npx
      args: ["-y", "@modelcontextprotocol/server-filesystem"]
      env: {}
plugins:
  marketplaces:
    - id: openai
      source: github:openai/codex-plugins
      autoUpdate: true
  enabled:
    - id: browser-use@openai
      scope: project
hooks:
  pre-commit:
    run: npm test
  SessionStart:
    - run: echo session
      timeout: 3
      statusMessage: Starting autonomous run
adapters:
  codex:
    target: .
  claude-code:
    target: .
    capabilities:
      - claude_md
      - agents
      - commands
      - docs
      - hooks
      - mcp
      - plugins
      - reference_projects
      - rules
      - scripts
      - skills
      - metrics
    agents_source: ./agents
    commands_source: ./commands
    docs_source: ./docs
    metrics_source: ./metrics
    rules_source: ./rules
    scripts_source: ./scripts
    skills_source: ./skills
`
    );

    const syncResult = await runSync(rootDir);
    const manifest = await loadManifest(rootDir);
    const settings = await readJson(rootDir, ".claude/settings.json");
    const hooks = asObject(settings.hooks);
    const sessionStart = asArray(hooks.SessionStart);
    const firstSessionStart = asObject(sessionStart[0]);
    const sessionStartCommands = asArray(firstSessionStart.hooks);
    const firstSessionCommand = asObject(sessionStartCommands[0]);
    const mcpServers = asObject(settings.mcpServers);
    const marketplaces = asObject(settings.marketplaces);
    const openaiMarketplace = asObject(marketplaces.openai);
    const plugins = asArray(settings.plugins);
    const firstPlugin = asObject(plugins[0]);
    const permissions = asObject(settings.permissions);
    const sandbox = asObject(settings.sandbox);
    const filesystem = asObject(sandbox.filesystem);
    const hook = await readText(rootDir, ".git/hooks/pre-commit");
    const manifestByPath = new Map(manifest.files.map((entry) => [entry.path, entry]));
    const afterSyncDiff = await runDiff(rootDir);

    expect(changedPaths(syncResult)).toContain(".claude/settings.json");
    expect(await exists(rootDir, "AGENTS.md")).toBe(true);
    expect(await exists(rootDir, ".codex/config.toml")).toBe(true);
    expect(await exists(rootDir, "CLAUDE.md")).toBe(true);
    expect(await exists(rootDir, ".claude/agents/reviewer.md")).toBe(true);
    expect(await exists(rootDir, ".claude/commands/review.md")).toBe(true);
    expect(await exists(rootDir, ".claude/docs/README.md")).toBe(true);
    expect(await exists(rootDir, ".claude/docs/archive/old.md")).toBe(false);
    expect(await exists(rootDir, ".claude/metrics/events.schema.md")).toBe(true);
    expect(await exists(rootDir, ".claude/metrics/events.jsonl")).toBe(false);
    expect(await exists(rootDir, ".claude/reference-project.json")).toBe(true);
    expect(await exists(rootDir, ".claude/rules/style.md")).toBe(true);
    expect(await exists(rootDir, ".claude/scripts/check.sh")).toBe(true);
    expect(await exists(rootDir, ".claude/skills/atom-example/SKILL.md")).toBe(true);
    expect(await exists(rootDir, ".git/hooks/pre-commit")).toBe(true);
    expect(hook).toContain("generated by harness; do not edit");
    expect(hook).toContain("npm test");
    expect(firstSessionCommand.command).toBe("echo session");
    expect(firstSessionCommand.timeout).toBe(3);
    expect(firstSessionCommand.statusMessage).toBe("Starting autonomous run");
    expect(Object.keys(mcpServers)).toEqual(["alpha", "beta"]);
    expect(openaiMarketplace.source).toBe("github:openai/codex-plugins");
    expect(openaiMarketplace.autoUpdate).toBe(true);
    expect(firstPlugin.plugin).toBe("browser-use@openai");
    expect(firstPlugin.scope).toBe("project");
    expect(firstPlugin.enabled).toBe(true);
    expect(asArray(permissions.deny)).toEqual(["Read(./docs/archive)", "Read(./docs/archive/**)"]);
    expect(filesystem.denyRead).toEqual(["./docs/archive", "./docs/archive/**"]);
    expect(manifestByPath.get(".claude/settings.json")?.kind).toBe("partial-json");
    expect(manifestByPath.get(".claude/settings.json")?.owned_keys).toEqual([
      "hooks",
      "marketplaces",
      "mcpServers",
      "permissions",
      "plugins",
      "sandbox"
    ]);
    expect(manifestByPath.get(".git/hooks/pre-commit")?.mode).toBe(0o755);
    expect(changedPaths(afterSyncDiff)).toEqual([]);
    expect(afterSyncDiff.unchanged.map((entry) => entry.path).sort((left, right) => left.localeCompare(right))).toEqual(manifestPaths(manifest));
  });

  it("locks manifest cleanup for removed generated full files and partial-json owned keys", async () => {
    const rootDir = await createWorkspace("harness-autonomous-manifest-");
    await writeText(rootDir, "AGENTS.md.template", "# Manifest fixture\n");
    await writeText(
      rootDir,
      "harness.yaml",
      `
name: autonomous-manifest-cleanup
tools:
  - claude-code
canonical:
  instructions: ./AGENTS.md.template
hooks:
  SessionStart:
    - run: echo session
adapters:
  claude-code:
    target: .
    capabilities:
      - claude_md
      - hooks
`
    );

    await runSync(rootDir);
    const settingsBeforeCleanup = await readJson(rootDir, ".claude/settings.json");
    await writeText(
      rootDir,
      ".claude/settings.json",
      `${JSON.stringify({ userPreference: true, ...settingsBeforeCleanup }, null, 2)}\n`
    );
    await writeText(
      rootDir,
      "harness.yaml",
      `
name: autonomous-manifest-cleanup
tools: []
canonical:
  instructions: ./AGENTS.md.template
adapters: {}
`
    );

    const cleanupResult = await runSync(rootDir);
    const settingsAfterCleanup = await readJson(rootDir, ".claude/settings.json");
    const manifestAfterCleanup = await loadManifest(rootDir);

    expect(cleanupResult.removed.map((entry) => entry.path).sort((left, right) => left.localeCompare(right))).toEqual([
      ".claude/settings.json",
      "CLAUDE.md"
    ]);
    expect(await exists(rootDir, "CLAUDE.md")).toBe(false);
    expect(settingsAfterCleanup).toEqual({ userPreference: true });
    expect(manifestAfterCleanup.files).toEqual([]);
  });

  it("leaves compound skill phase frontmatter untouched during sync", async () => {
    const rootDir = await createWorkspace("harness-autonomous-phases-");
    const skillSource = `---
name: compound-example
phases:
  - phase_id: architect
    agent: architect
    tool: claude-code
    cwd_ref: harness
  - phase_id: android-coder
    agent: android-coder
    tool: codex
    cwd_ref: target:android
    parallel_group: platform-coders
---
# Compound Example

Keep the phase spec in frontmatter.
`;
    await writeText(rootDir, "AGENTS.md.template", "# Phase fixture\n");
    await writeText(rootDir, "skills/compound/compound-example/SKILL.md", skillSource);
    await writeText(
      rootDir,
      "harness.yaml",
      `
name: autonomous-phase-sync
tools:
  - claude-code
canonical:
  instructions: ./AGENTS.md.template
adapters:
  claude-code:
    target: .
    capabilities:
      - skills
    skills_source: ./skills
`
    );

    await runSync(rootDir);

    expect(await readText(rootDir, ".claude/skills/compound/compound-example/SKILL.md")).toBe(skillSource);
  });
});
