import { chmod, mkdtemp, mkdir, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { planClaudeScriptsDirectory } from "../src/adapters/claude-scripts.js";

async function createRootDir(): Promise<string> {
  return mkdtemp(path.join(os.tmpdir(), "harness-claude-scripts-"));
}

describe("claude scripts scan", () => {
  it("returns an empty plan for an empty scripts source", async () => {
    const rootDir = await createRootDir();
    await mkdir(path.join(rootDir, "claude", "scripts"), { recursive: true });

    await expect(planClaudeScriptsDirectory(rootDir, rootDir, "./claude/scripts")).resolves.toEqual([]);
  });

  it("returns an empty plan when the scripts source directory does not exist", async () => {
    const rootDir = await createRootDir();

    await expect(planClaudeScriptsDirectory(rootDir, rootDir, "./claude/scripts")).resolves.toEqual([]);
  });

  it("copies mixed script assets while only injecting markers into markdown", async () => {
    const rootDir = await createRootDir();
    await mkdir(path.join(rootDir, "claude", "scripts"), { recursive: true });
    await writeFile(path.join(rootDir, "claude", "scripts", "check.sh"), "#!/usr/bin/env bash\necho hi\n", "utf8");
    await writeFile(path.join(rootDir, "claude", "scripts", "helper.py"), "print('hi')\n", "utf8");
    await writeFile(path.join(rootDir, "claude", "scripts", "notes.md"), "Notes.\n", "utf8");
    await chmod(path.join(rootDir, "claude", "scripts", "check.sh"), 0o755);

    const plan = await planClaudeScriptsDirectory(rootDir, rootDir, "./claude/scripts");
    const shellFile = plan.find((file) => file.path === ".claude/scripts/check.sh");
    const pythonFile = plan.find((file) => file.path === ".claude/scripts/helper.py");
    const markdownFile = plan.find((file) => file.path === ".claude/scripts/notes.md");

    expect(plan).toHaveLength(3);
    expect(shellFile?.content).toBeInstanceOf(Uint8Array);
    expect(pythonFile?.content).toBeInstanceOf(Uint8Array);
    expect(markdownFile?.content).toBe("<!-- generated by harness; do not edit. Source: claude/scripts/notes.md -->\nNotes.\n");
    expect(shellFile?.mode).toBe(0o755);
  });

  it("recursively mirrors nested script resources and injects markers into nested markdown", async () => {
    const rootDir = await createRootDir();
    await mkdir(path.join(rootDir, "claude", "scripts", "metrics"), { recursive: true });
    await writeFile(path.join(rootDir, "claude", "scripts", "session-start-check.sh"), "#!/usr/bin/env bash\necho session\n", "utf8");
    await chmod(path.join(rootDir, "claude", "scripts", "session-start-check.sh"), 0o755);
    await writeFile(path.join(rootDir, "claude", "scripts", "metrics", "template.md"), "metric template\n", "utf8");

    const plan = await planClaudeScriptsDirectory(rootDir, rootDir, "./claude/scripts");
    const nestedMarkdown = plan.find((file) => file.path === ".claude/scripts/metrics/template.md");

    expect(plan).toHaveLength(2);
    expect(nestedMarkdown?.content).toBe(
      "<!-- generated by harness; do not edit. Source: claude/scripts/metrics/template.md -->\nmetric template\n"
    );
  });

  it("skips symlinks and hidden files with warnings", async () => {
    const rootDir = await createRootDir();
    const warnings: string[] = [];
    await mkdir(path.join(rootDir, "claude", "scripts"), { recursive: true });
    await writeFile(path.join(rootDir, "claude", "scripts", "real.sh"), "#!/usr/bin/env bash\necho real\n", "utf8");
    await writeFile(path.join(rootDir, "claude", "scripts", ".DS_Store"), "ignored\n", "utf8");
    await symlink(path.join(rootDir, "claude", "scripts", "real.sh"), path.join(rootDir, "claude", "scripts", "real-link.sh"));

    const plan = await planClaudeScriptsDirectory(rootDir, rootDir, "./claude/scripts", {
      onWarning(message) {
        warnings.push(message);
      }
    });

    expect(plan.map((file) => file.path)).toEqual([".claude/scripts/real.sh"]);
    expect(warnings).toEqual(["Warning: claude-code adapter skip symlink: claude/scripts/real-link.sh"]);
  });

  it("fails with a named error when a source file cannot be read", async () => {
    const rootDir = await createRootDir();
    await mkdir(path.join(rootDir, "claude", "scripts"), { recursive: true });
    await writeFile(path.join(rootDir, "claude", "scripts", "private.sh"), "#!/usr/bin/env bash\necho secret\n", "utf8");
    await chmod(path.join(rootDir, "claude", "scripts", "private.sh"), 0o000);

    await expect(planClaudeScriptsDirectory(rootDir, rootDir, "./claude/scripts")).rejects.toMatchObject({
      code: "ADAPTER_SOURCE_READ_FAILED",
      message: "Adapter `claude-code` could not read source file: claude/scripts/private.sh"
    });
  });
});
