import { chmod, mkdtemp, mkdir, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { planClaudeSkillsDirectory } from "../src/adapters/claude-skills.js";

async function createRootDir(): Promise<string> {
  return mkdtemp(path.join(os.tmpdir(), "harness-claude-skills-"));
}

describe("claude skills scan", () => {
  it("returns an empty plan for an empty skills source", async () => {
    const rootDir = await createRootDir();
    await mkdir(path.join(rootDir, "claude", "skills"), { recursive: true });

    await expect(planClaudeSkillsDirectory(rootDir, rootDir, "./claude/skills")).resolves.toEqual([]);
  });

  it("returns an empty plan when the skills source directory does not exist", async () => {
    const rootDir = await createRootDir();

    await expect(planClaudeSkillsDirectory(rootDir, rootDir, "./claude/skills")).resolves.toEqual([]);
  });

  it("plans a single SKILL.md file and injects the generated marker", async () => {
    const rootDir = await createRootDir();
    await mkdir(path.join(rootDir, "claude", "skills", "code-review"), { recursive: true });
    await writeFile(path.join(rootDir, "claude", "skills", "code-review", "SKILL.md"), "Run code review.\n", "utf8");

    const plan = await planClaudeSkillsDirectory(rootDir, rootDir, "./claude/skills");

    expect(plan).toHaveLength(1);
    expect(plan[0]?.path).toBe(".claude/skills/code-review/SKILL.md");
    expect(plan[0]?.content).toBe("<!-- generated by harness; do not edit. Source: claude/skills/code-review/SKILL.md -->\nRun code review.\n");
  });

  it("copies mixed skill assets while only injecting markers into markdown", async () => {
    const rootDir = await createRootDir();
    await mkdir(path.join(rootDir, "claude", "skills", "code-review"), { recursive: true });
    await writeFile(path.join(rootDir, "claude", "skills", "code-review", "SKILL.md"), "Run code review.\n", "utf8");
    await writeFile(path.join(rootDir, "claude", "skills", "code-review", "helper.sh"), "#!/usr/bin/env bash\necho hi\n", "utf8");
    await writeFile(path.join(rootDir, "claude", "skills", "code-review", "data.json"), '{"ok":true}\n', "utf8");
    await chmod(path.join(rootDir, "claude", "skills", "code-review", "helper.sh"), 0o755);

    const plan = await planClaudeSkillsDirectory(rootDir, rootDir, "./claude/skills");
    const skillFile = plan.find((file) => file.path === ".claude/skills/code-review/SKILL.md");
    const helperFile = plan.find((file) => file.path === ".claude/skills/code-review/helper.sh");
    const dataFile = plan.find((file) => file.path === ".claude/skills/code-review/data.json");

    expect(plan).toHaveLength(3);
    expect(skillFile?.content).toBe("<!-- generated by harness; do not edit. Source: claude/skills/code-review/SKILL.md -->\nRun code review.\n");
    expect(helperFile?.content).toBeInstanceOf(Uint8Array);
    expect(dataFile?.content).toBeInstanceOf(Uint8Array);
    expect(helperFile?.mode).toBe(0o755);
  });

  it("recursively plans nested markdown resources and injects the correct source marker", async () => {
    const rootDir = await createRootDir();
    await mkdir(path.join(rootDir, "claude", "skills", "code-review", "resources"), { recursive: true });
    await mkdir(path.join(rootDir, "claude", "skills", "code-review", "scripts"), { recursive: true });
    await writeFile(
      path.join(rootDir, "claude", "skills", "code-review", "SKILL.md"),
      "---\nname: code-review\n---\nRun code review.\n",
      "utf8"
    );
    await writeFile(path.join(rootDir, "claude", "skills", "code-review", "resources", "template.md"), "Template.\n", "utf8");
    await writeFile(path.join(rootDir, "claude", "skills", "code-review", "scripts", "analyze.sh"), "#!/usr/bin/env bash\necho analyze\n", "utf8");
    await writeFile(path.join(rootDir, "claude", "skills", "code-review", "config.json"), '{"name":"review"}\n', "utf8");

    const plan = await planClaudeSkillsDirectory(rootDir, rootDir, "./claude/skills");
    const nestedMarkdown = plan.find((file) => file.path === ".claude/skills/code-review/resources/template.md");

    expect(plan).toHaveLength(4);
    expect(nestedMarkdown?.content).toBe(
      "<!-- generated by harness; do not edit. Source: claude/skills/code-review/resources/template.md -->\nTemplate.\n"
    );
  });

  it("skips symlinks, hidden files, and loose markdown files with warnings", async () => {
    const rootDir = await createRootDir();
    const warnings: string[] = [];
    await mkdir(path.join(rootDir, "claude", "skills", "code-review"), { recursive: true });
    await writeFile(path.join(rootDir, "claude", "skills", "code-review", "SKILL.md"), "Run code review.\n", "utf8");
    await writeFile(path.join(rootDir, "claude", "skills", "loose.md"), "Loose.\n", "utf8");
    await writeFile(path.join(rootDir, "claude", "skills", ".DS_Store"), "ignored\n", "utf8");
    await symlink(
      path.join(rootDir, "claude", "skills", "code-review", "SKILL.md"),
      path.join(rootDir, "claude", "skills", "code-review", "skill-link.md")
    );

    const plan = await planClaudeSkillsDirectory(rootDir, rootDir, "./claude/skills", {
      onWarning(message) {
        warnings.push(message);
      }
    });

    expect(plan.map((file) => file.path)).toEqual([".claude/skills/code-review/SKILL.md"]);
    expect(warnings).toEqual([
      "Warning: claude-code adapter skip symlink: claude/skills/code-review/skill-link.md",
      "Warning: claude-code adapter skill must be a directory: claude/skills/loose.md"
    ]);
  });

  it("warns when a skill path becomes deeply nested", async () => {
    const rootDir = await createRootDir();
    const warnings: string[] = [];
    await mkdir(path.join(rootDir, "claude", "skills", "code-review", "a", "b", "c", "d", "e", "f"), { recursive: true });
    await writeFile(path.join(rootDir, "claude", "skills", "code-review", "a", "b", "c", "d", "e", "f", "deep.md"), "Deep.\n", "utf8");

    const plan = await planClaudeSkillsDirectory(rootDir, rootDir, "./claude/skills", {
      onWarning(message) {
        warnings.push(message);
      }
    });

    expect(plan.map((file) => file.path)).toEqual([".claude/skills/code-review/a/b/c/d/e/f/deep.md"]);
    expect(warnings).toEqual(["Warning: claude-code adapter detected deep skill path (>6): code-review/a/b/c/d/e/f/deep.md"]);
  });
});
