import path from "node:path";

import * as TOML from "@iarna/toml";
import { describe, expect, it } from "vitest";

import { createCodexAdapter, parseHarnessConfig } from "../src/index.js";

describe("codex adapter", () => {
  it("plans generated agents and codex config files", async () => {
    const adapter = createCodexAdapter();
    const rootDir = path.resolve("packages/core/tests/fixtures/self-host");
    const config = parseHarnessConfig(`
name: harness-cli
tools:
  - codex
canonical:
  instructions: ./AGENTS.md.template
  codexConfig: ./.codex/config.toml.template
adapters:
  codex:
    target: .
`);

    const plan = await adapter.plan(config, rootDir);
    const agentsFile = plan.find((file) => file.path === "AGENTS.md");
    const configFile = plan.find((file) => file.path === ".codex/config.toml");

    expect(plan).toHaveLength(2);
    expect(agentsFile?.content.startsWith("<!-- generated by harness; do not edit -->")).toBe(true);
    expect(configFile?.content).toContain('inherit = "core"');
    expect(configFile?.content).not.toContain("[mcp_servers.");
  });

  it("appends sorted MCP server blocks to the generated codex config", async () => {
    const adapter = createCodexAdapter();
    const rootDir = path.resolve("packages/core/tests/fixtures/self-host");
    const config = parseHarnessConfig(`
name: harness-cli
tools:
  - codex
canonical:
  instructions: ./AGENTS.md.template
  codexConfig: ./.codex/config.toml.template
mcp:
  servers:
    beta:
      command: node
      args: []
      env: {}
    alpha:
      command: npx
      args: ["-y", "@modelcontextprotocol/server-github"]
      env:
        Z_TOKEN: "\${Z_TOKEN}"
        A_TOKEN: "\${A_TOKEN}"
adapters:
  codex:
    target: .
`);

    const plan = await adapter.plan(config, rootDir);
    const configFile = plan.find((file) => file.path === ".codex/config.toml");
    const content = configFile?.content ?? "";

    expect(content).toContain('[mcp_servers.alpha]');
    expect(content).toContain('[mcp_servers.beta]');
    expect(content.indexOf('[mcp_servers.alpha]')).toBeLessThan(content.indexOf('[mcp_servers.beta]'));
    expect(content).toContain('args = [ "-y", "@modelcontextprotocol/server-github" ]');
    expect(content).toContain('args = [ ]');
    expect(content).toContain('env = { A_TOKEN = "${A_TOKEN}", Z_TOKEN = "${Z_TOKEN}" }');
    expect(content).toContain('env = { }');
  });

  it("renders no-active-context read denials in codex config", async () => {
    const adapter = createCodexAdapter();
    const rootDir = path.resolve("packages/core/tests/fixtures/self-host");
    const config = parseHarnessConfig(`
name: harness-cli
tools:
  - codex
canonical:
  instructions: ./AGENTS.md.template
context:
  no_active_context:
    - path: docs/archive/
      reason: Historical experiment output.
    - path: docs/research/**
      mode: soft_ignore
adapters:
  codex:
    target: .
`);

    const plan = await adapter.plan(config, rootDir);
    const configFile = plan.find((file) => file.path === ".codex/config.toml");
    const content = configFile?.content ?? "";

    expect(configFile).toBeDefined();
    expect(() => TOML.parse(content)).not.toThrow();
    expect(content).toContain('default_permissions = "harness-no-active-context"');
    expect(content).toContain("[permissions.harness-no-active-context.filesystem]");
    expect(content).toContain('":project_roots" = { "." = "write", "docs/archive" = "none", "docs/archive/**" = "none" }');
    expect(content).not.toContain("docs/research");
  });

  it("renders profiles only for agents routed to Codex", async () => {
    const adapter = createCodexAdapter();
    const rootDir = path.resolve("packages/core/tests/fixtures/self-host");
    const config = parseHarnessConfig(`
schema_version: 2
name: harness-cli
tools:
  - claude-code
  - codex
canonical:
  instructions: ./AGENTS.md.template
  codexConfig: ./.codex/config.toml.template
agent_tools:
  default: claude-code
  agents:
    architect: claude-code
    android-coder: codex
    code-reviewer: codex
models:
  codex:
    default:
      model: gpt-5-codex
      effort: medium
      sandbox_mode: workspace-write
      approval_policy: never
    agents:
      architect:
        effort: high
      android-coder:
        effort: high
      code-reviewer:
        sandbox_mode: read-only
        approval_policy: on-request
adapters:
  codex:
    target: .
`);

    const plan = await adapter.plan(config, rootDir);
    const configFile = plan.find((file) => file.path === ".codex/config.toml");
    const content = configFile?.content ?? "";
    const parsed = TOML.parse(content) as { readonly profiles?: Record<string, Record<string, unknown>> };

    expect(Object.keys(parsed.profiles ?? {}).sort((left, right) => left.localeCompare(right))).toEqual([
      "android-coder",
      "code-reviewer"
    ]);
    expect(parsed.profiles?.["android-coder"]).toEqual({
      model: "gpt-5-codex",
      model_reasoning_effort: "high",
      sandbox_mode: "workspace-write",
      approval_policy: "never"
    });
    expect(parsed.profiles?.["code-reviewer"]).toEqual({
      model: "gpt-5-codex",
      model_reasoning_effort: "medium",
      sandbox_mode: "read-only",
      approval_policy: "on-request"
    });
    expect(content).not.toContain("[profiles.architect]");
  });
});
