import path from "node:path";

import { describe, expect, it } from "vitest";

import { createCursorAdapter, parseHarnessConfig } from "../src/index.js";

describe("cursor adapter", () => {
  it("plans a cursor rules file with frontmatter, marker, and canonical body", async () => {
    const adapter = createCursorAdapter();
    const rootDir = path.resolve("packages/core/tests/fixtures/self-host");
    const config = parseHarnessConfig(`
name: harness-cli
tools:
  - cursor
canonical:
  instructions: ./AGENTS.md.template
adapters:
  cursor:
    target: .
`);

    const plan = await adapter.plan(config, rootDir);

    expect(plan).toHaveLength(1);
    expect(plan[0]?.path).toBe(".cursor/rules/main.mdc");
    expect(plan.some((file) => file.path === ".cursor/mcp.json")).toBe(false);
    expect(plan[0]?.content).toContain('description: Harness-managed development rules');
    expect(plan[0]?.content).toContain("alwaysApply: true");
    expect(plan[0]?.content).toContain("<!-- generated by harness; do not edit -->");
    expect(plan[0]?.content).toContain("# harness-cli Agent Guide");
  });

  it("adds a sorted .cursor/mcp.json when MCP servers are declared", async () => {
    const adapter = createCursorAdapter();
    const rootDir = path.resolve("packages/core/tests/fixtures/self-host");
    const config = parseHarnessConfig(`
name: harness-cli
tools:
  - cursor
canonical:
  instructions: ./AGENTS.md.template
mcp:
  servers:
    beta:
      command: node
      args: ["b"]
      env:
        Z_TOKEN: "\${Z_TOKEN}"
        A_TOKEN: "\${A_TOKEN}"
    alpha:
      command: npx
      args: []
      env: {}
adapters:
  cursor:
    target: .
`);

    const plan = await adapter.plan(config, rootDir);
    const mcpFile = plan.find((file) => file.path === ".cursor/mcp.json");
    const content = mcpFile?.content ?? "";

    expect(mcpFile).toBeDefined();
    expect(content.indexOf('"alpha"')).toBeLessThan(content.indexOf('"beta"'));
    expect(JSON.parse(content)).toEqual({
      mcpServers: {
        alpha: {
          command: "npx",
          args: [],
          env: {}
        },
        beta: {
          command: "node",
          args: ["b"],
          env: {
            A_TOKEN: "${A_TOKEN}",
            Z_TOKEN: "${Z_TOKEN}"
          }
        }
      }
    });
  });

  it("renders an empty MCP JSON document when MCP is explicitly declared with zero servers", async () => {
    const adapter = createCursorAdapter();
    const rootDir = path.resolve("packages/core/tests/fixtures/self-host");
    const config = parseHarnessConfig(`
name: harness-cli
tools:
  - cursor
canonical:
  instructions: ./AGENTS.md.template
mcp:
  servers: {}
adapters:
  cursor:
    target: .
`);

    const plan = await adapter.plan(config, rootDir);
    const mcpFile = plan.find((file) => file.path === ".cursor/mcp.json");

    expect(mcpFile?.content).toBe('{\n  "mcpServers": {}\n}\n');
  });

  it("throws a typed error when the canonical instructions file is missing", async () => {
    const adapter = createCursorAdapter();
    const rootDir = path.resolve("packages/core/tests/fixtures/self-host");
    const config = parseHarnessConfig(`
name: harness-cli
tools:
  - cursor
canonical:
  instructions: ./missing-template.md
adapters:
  cursor:
    target: .
`);

    await expect(adapter.plan(config, rootDir)).rejects.toMatchObject({
      code: "ADAPTER_TEMPLATE_MISSING",
      message: expect.stringContaining("missing-template.md")
    });
  });
});
