import { mkdtemp, mkdir } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { parseHarnessConfig, planHooks } from "../src/index.js";

describe("hook planner", () => {
  it("returns an empty plan when no hooks are configured", async () => {
    const rootDir = await mkdtemp(path.join(os.tmpdir(), "harness-hooks-empty-"));
    const config = parseHarnessConfig(`
name: demo
tools:
  - codex
canonical:
  instructions: ./AGENTS.md.template
`);

    await expect(planHooks(config, rootDir)).resolves.toEqual([]);
  });

  it("plans a pre-commit hook with executable mode and generated content", async () => {
    const rootDir = await mkdtemp(path.join(os.tmpdir(), "harness-hooks-pre-commit-"));
    await mkdir(path.join(rootDir, ".git", "hooks"), { recursive: true });
    const config = parseHarnessConfig(`
name: demo
tools:
  - codex
canonical:
  instructions: ./AGENTS.md.template
hooks:
  pre-commit:
    run: |
      set -e
      harness diff --check
`);

    const plan = await planHooks(config, rootDir);

    expect(plan).toHaveLength(1);
    expect(plan[0]).toMatchObject({
      path: ".git/hooks/pre-commit",
      mode: 0o755
    });
    expect(plan[0]?.content).toBe(
      "#!/usr/bin/env bash\n# generated by harness; do not edit\n# source: harness.yaml hooks.pre-commit\nset -e\nharness diff --check\n"
    );
  });

  it("skips disabled pre-commit hooks", async () => {
    const rootDir = await mkdtemp(path.join(os.tmpdir(), "harness-hooks-disabled-"));
    await mkdir(path.join(rootDir, ".git", "hooks"), { recursive: true });
    const config = parseHarnessConfig(`
name: demo
tools:
  - codex
canonical:
  instructions: ./AGENTS.md.template
hooks:
  pre-commit:
    enabled: false
    run: echo hi
`);

    await expect(planHooks(config, rootDir)).resolves.toEqual([]);
  });

  it("rejects unsupported hook shells through zod validation", () => {
    expect(() =>
      parseHarnessConfig(`
name: demo
tools:
  - codex
canonical:
  instructions: ./AGENTS.md.template
hooks:
  pre-commit:
    shell: zsh
    run: echo hi
`)
    ).toThrow(/bash/);
  });
});
