import { access } from "node:fs/promises";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { runDiff, runSync } from "../src/index.js";

import { copyFixture, readText } from "./helpers.js";

describe("self-host sync integration", () => {
  it("keeps a codex workspace idempotent and writes manifest on first sync", async () => {
    const rootDir = await copyFixture(path.resolve("packages/core/tests/fixtures/self-host"));

    const diffResult = await runDiff(rootDir);
    expect(diffResult).toEqual({
      added: [],
      modified: [],
      removed: [],
      unchanged: [
        { path: ".codex/config.toml", reason: "sha256-match" },
        { path: "AGENTS.md", reason: "sha256-match" }
      ]
    });

    const firstSync = await runSync(rootDir);
    const secondSync = await runSync(rootDir);
    const dryRunSync = await runSync(rootDir, { dryRun: true });
    const manifestPath = path.join(rootDir, ".harness/manifest.json");

    expect(firstSync.added).toEqual([]);
    expect(firstSync.modified).toEqual([]);
    expect(firstSync.removed).toEqual([]);
    expect(firstSync.unchanged).toHaveLength(2);
    expect(secondSync).toEqual(firstSync);
    expect(dryRunSync).toEqual(diffResult);
    await expect(access(manifestPath)).resolves.toBeUndefined();
    await expect(readText(path.join(rootDir, "AGENTS.md"))).resolves.toContain("<!-- generated by harness; do not edit -->");
  });
});
