import * as TOML from "@iarna/toml";

import type { HarnessConfig } from "./harness-config.js";

type ContextVisibilityRule = NonNullable<NonNullable<HarnessConfig["context"]>["no_active_context"]>[number];
const CODEX_NO_ACTIVE_CONTEXT_PROFILE = "harness-no-active-context";

function toPortablePath(value: string): string {
  return value.replace(/\\/g, "/");
}

function stripProjectRelativePrefix(value: string): string {
  return value.startsWith("./") ? value.slice(2) : value;
}

function stripTrailingSlash(value: string): string {
  return value.replace(/\/+$/g, "");
}

function expandDirectoryLikePath(rawPath: string): string[] {
  const portablePath = stripProjectRelativePrefix(toPortablePath(rawPath.trim()));

  if (portablePath.length === 0) {
    return [];
  }

  if (portablePath.endsWith("/**")) {
    const directoryPath = stripTrailingSlash(portablePath.slice(0, -3));
    return directoryPath.length > 0 ? [directoryPath, portablePath] : [portablePath];
  }

  if (portablePath.endsWith("/")) {
    const directoryPath = stripTrailingSlash(portablePath);
    return directoryPath.length > 0 ? [directoryPath, `${directoryPath}/**`] : [];
  }

  return [portablePath];
}

function sortUnique(values: readonly string[]): string[] {
  return [...new Set(values)].sort((left, right) => left.localeCompare(right));
}

function denyReadRules(config: HarnessConfig): ContextVisibilityRule[] {
  return (config.context?.no_active_context ?? []).filter((rule) => rule.mode === "deny_read");
}

export function getNoActiveContextDenyReadPaths(config: HarnessConfig): string[] {
  return sortUnique(denyReadRules(config).flatMap((rule) => expandDirectoryLikePath(rule.path)));
}

export function hasNoActiveContextDenyRead(config: HarnessConfig): boolean {
  return getNoActiveContextDenyReadPaths(config).length > 0;
}

export function isNoActiveContextDenyReadPath(config: HarnessConfig, relativePath: string): boolean {
  const portablePath = stripTrailingSlash(stripProjectRelativePrefix(toPortablePath(relativePath.trim())));

  if (portablePath.length === 0) {
    return false;
  }

  return getNoActiveContextDenyReadPaths(config).some((pattern) => {
    if (pattern.endsWith("/**")) {
      const directoryPath = stripTrailingSlash(pattern.slice(0, -3));
      return portablePath === directoryPath || portablePath.startsWith(`${directoryPath}/`);
    }

    return portablePath === stripTrailingSlash(pattern);
  });
}

function toClaudeProjectPath(value: string): string {
  if (value.startsWith("/") || value.startsWith("~/") || value.startsWith("./")) {
    return value;
  }

  return `./${value}`;
}

export function renderClaudeNoActiveContextSettings(config: HarnessConfig): Record<string, unknown> {
  const paths = getNoActiveContextDenyReadPaths(config).map(toClaudeProjectPath);

  if (paths.length === 0) {
    return {};
  }

  return {
    permissions: {
      deny: paths.map((entry) => `Read(${entry})`)
    },
    sandbox: {
      filesystem: {
        denyRead: paths
      }
    }
  };
}

export function renderCodexNoActiveContextFragment(config: HarnessConfig): string {
  const paths = getNoActiveContextDenyReadPaths(config);

  if (paths.length === 0) {
    return "";
  }

  const projectRootPermissions = {
    ".": "write",
    ...Object.fromEntries(paths.map((entry) => [entry, "none"]))
  };

  return [
    "# Generated by harness: no-active-context paths are denied for filesystem reads.",
    `default_permissions = ${TOML.stringify.value(CODEX_NO_ACTIVE_CONTEXT_PROFILE)}`,
    `[permissions.${CODEX_NO_ACTIVE_CONTEXT_PROFILE}.filesystem]`,
    `":project_roots" = ${TOML.stringify.value(projectRootPermissions)}`
  ].join("\n");
}
