export const CLI_COMMANDS = Object.freeze({
  ADOPT: "adopt",
  ADAPTERS: "adapters",
  DIFF: "diff",
  DOCTOR: "doctor",
  EVAL: "eval",
  HELP: "help",
  INIT: "init",
  KM_PAGE_ANALYSIS: "km-page-analysis",
  KM_MODULE_DESIGN: "km-module-design",
  RUN: "run",
  SYNC: "sync",
  VERSION: "version",
});

export const HELP_TEXT = [
  "Usage: harness <command> [options]",
  "",
  "Commands:",
  "  adopt     Reverse-migrate an existing .claude/ workspace into a harness repository",
  "  adapters  Inspect registered adapters and exported capability contracts",
  "  diff      Show harness-managed drift without writing files",
  "  doctor    Run environment checks from harness.yaml",
  "  eval      Ingest and inspect post-hoc trajectory logs",
  "  help      Show this help message",
  "  init      Scaffold a new harness repository for the codex adapter",
  "  km-page-analysis Analyze page modules, dependencies, and km-module-design order",
  "  km-module-design Prepare, run, validate, and clean km-module-design workflows",
  "  run       Dry-run autonomous phase specs and inspect run artifacts",
  "  sync      Reconcile harness-managed files into the workspace",
  "  version   Show CLI version",
  "",
  "Options:",
  "  --check          Return exit 1 when `harness diff` finds drift",
  "  --json           Print machine-readable output",
  "  --config <path>  Use a non-default harness config file",
  "  --harness-repo <path>  Read harness.yaml and source assets from another repository",
  "  --no-local      Skip harness.local.yaml local overrides for sync/diff",
  "  --dry-run        Preview sync without writing files",
  "  --adopt-settings Allow sync to take ownership of existing .claude/settings.json keys",
  "  --force          Allow init to write into a non-empty target directory",
  "  --in-place       Initialize the current directory instead of ./<name>",
  "  --compound <name>  Select skills/compound/<name>/SKILL.md for run",
  "  --skill <path>   Select a SKILL.md file for run",
  "  --thread-id <id> Set thread id for run-root calculation",
  "  --run-root <path> Override .harness/runs/<thread-id> for run commands",
  "  --run-id <id>      Select a run id for commands that write/read run roots",
  "  --brief <path>   Read a Markdown brief file for real `harness run` execution",
  "  --prompt <text>  Inline brief text for real `harness run` execution",
  "  --task-card <path> Read a JSON/YAML TaskCard for bounded execution",
  "  --resume <id>    Resume a paused autonomous run from .harness/runs/<id>",
  "  --judge-tool <tool> Enable provider-backed audit/checkpoint judge (claude-code or codex)",
  "  --judge-profile <profile> Use a Codex profile for provider-backed judge calls",
  "  --scope <value>  Set harness scope (project or global)",
  "  --help           Show help for a command",
  "  --version        Show CLI version",
].join("\n");

export const INIT_HELP_TEXT = [
  "Usage: harness init [name] [--in-place] [--scope <project|global>] [--force] [--json]",
  "",
  "Scaffold a new harness repository with codex templates.",
  "",
  "Behavior:",
  "  - No name or --in-place: initialize the current directory",
  "  - With name: initialize ./<name>",
  "  - --force: overwrite harness-managed scaffold files in a non-empty target",
  "  - --scope global: write global scope into harness.yaml for later stages",
].join("\n");

export const ADAPTERS_HELP_TEXT = [
  "Usage: harness adapters <list|capabilities> [options]",
  "",
  "Commands:",
  "  list                        Show registered adapters for the current harness config",
  "  capabilities [adapter-id]   Show capability features for one adapter or all adapters",
  "",
  "Options:",
  "  --json           Print machine-readable output",
  "  --format json    Alias for --json",
  "  --config <path>  Use a non-default harness config file for `adapters list`",
  "  --help           Show this help message",
].join("\n");

export const EVAL_HELP_TEXT = [
  "Usage: harness eval <ingest|list|score|funnel|run|compare> [options]",
  "",
  "Commands:",
  "  ingest <jsonl-path>   Convert a trajectory jsonl file into an Inspect AI EvalLog",
  "  ingest --run <id>     Convert captured run phase trajectories into an Inspect AI EvalLog",
  "  list                  List stored EvalLog runs from .harness/logs/",
  "  run --scenario <id>   Execute evals/scenarios/<id>.yaml through harness run",
  "  compare --base <run-root> --head <run-root> Compare two run stores",
  "  score <run-id>        Recompute funnel scores for an existing EvalLog",
  "  funnel                Compute funnel scores directly from a trajectory and optional artifacts",
  "",
  "Options:",
  "  --scenario <id>       Scenario id for ingest output or list filtering",
  "  --scenario-id <id>    Alias for --scenario",
  "  --session-id <id>     Override session id inference for ingest",
  "  --source <name>       Trajectory source adapter (stub, claude-code, codex)",
  "  --run <thread-id>     Ingest captured trajectory from .harness/runs/<thread-id>",
  "  --run-root <path>     Override run root for eval ingest --run",
  "  --harness-repo <path> Resolve .harness/runs from another harness repository",
  "  --base <run-root>     Base run root for eval compare",
  "  --head <run-root>     Head run root for eval compare",
  "  --events <path>       Sailor review events jsonl for quality metrics",
  "  --bugs <path>         Markdown bug list for bug density scoring",
  "  --repo <path>         Repository root for LOC and rule counting",
  "  --lint <path>         Lint report JSON for tech design conformance",
  "  --smoke <path>        Smoke test report JSON for smoke pass rate",
  "  --format <value>      Funnel output format (`table` or `json`)",
  "  --json                Print machine-readable output",
  "  --help                Show this help message",
].join("\n");

export const RUN_HELP_TEXT = [
  "Usage: harness run (--compound <name> | --skill <path>) [options]",
  "       harness run --dry-run (--compound <name> | --skill <path>) [options]",
  "       harness run --resume <thread-id> [--compound <name> | --skill <path>] [options]",
  "       harness run inspect <thread-id> [options]",
  "       harness run view <thread-id> [options]",
  "",
  "Execute autonomous phase specs, validate them with --dry-run, or inspect captured run artifacts.",
  "",
  "Options:",
  "  --compound <name>  Read skills/compound/<name>/SKILL.md",
  "  --skill <path>     Read an explicit SKILL.md path relative to the harness repo",
  "  --thread-id <id>   Use a thread id when computing .harness/runs/<thread-id>",
  "  --run-id <id>      Override run id for real execution",
  "  --run-root <path>  Override the computed run root",
  "  --brief <path>     Read a Markdown brief file for real execution",
  "  --prompt <text>    Inline brief text for real execution",
  "  --task-card <path> Read a JSON/YAML TaskCard for bounded execution",
  "  --resume <id>      Resume a paused run after writing the decision file",
  "  --judge-tool <tool> Enable provider-backed audit/checkpoint judge (claude-code or codex)",
  "  --judge-profile <profile> Use a Codex profile for provider-backed judge calls",
  "  --judge-timeout-seconds <n> Timeout for provider-backed judge calls",
  "  --config <path>    Use a non-default harness config file",
  "  --harness-repo <path>  Read harness.yaml and source assets from another repository",
  "  --no-local         Skip harness.local.yaml local overrides",
  "  --json             Print machine-readable output",
  "",
  "Inspect/view options:",
  "  --run-root <path>  Read a specific run root",
  "  --harness-repo <path>  Resolve .harness/runs/<thread-id> from another repository",
  "  --json             Print machine-readable output",
  "  --help             Show this help message",
].join("\n");

export const KM_MODULE_DESIGN_HELP_TEXT = [
  "Usage: harness km-module-design <prepare|contributors|integrate|run|validate|status|clean> [options]",
  "",
  "Prepare and operate a three-contributor km-module-design workflow.",
  "",
  "Commands:",
  "  prepare       Create draft spec-pack manifest plus contributor prompts",
  "  contributors  Launch architect, machpro-parity, and tester in parallel",
  "  integrate     Launch architect-integrator for an existing run",
  "  run           Prepare and launch contributors; optionally integrate",
  "  validate      Run the target harness spec-pack validator",
  "  status        Print manifest and contributor status",
  "  clean         Remove run artifacts; pass --include-spec-pack to remove the module spec-package",
  "",
  "Options:",
  "  --harness-repo <path>  Target harness repository; defaults to cwd",
  "  --business <id>        Business id, for example shop",
  "  --module <id>          Module id, for example productlist",
  "  --source <id=path>     Source repo path; can be passed multiple times",
  "  --source-path <id=path> Source subpath inside a named source repo",
  "  --source-platform <id=name> Optional source platform label",
  "  --target <id=path>     Target repo path; id distinguishes android, ios, frontend, backend, etc.",
  "  --target-platform <id=name> Optional target platform label; defaults to id",
  "  --machpro-repo <path>  Deprecated alias for --source machpro=<path>",
  "  --machpro-path <path>  Deprecated alias for --source-path machpro=<path>",
  "  --android-repo <path>  Deprecated alias for --target android=<path>",
  "  --ios-repo <path>      Deprecated alias for --target ios=<path>",
  "  --run-id <id>          Stable run id; prepare/run default to timestamp",
  "  --force                Replace an existing draft spec-pack output",
  "  --agent-command-template <cmd>  Shell template using {agent}, {prompt_file}, {run_dir}, {harness_repo}, {business}, {module}, {output_dir}",
  "  --run-integrator       For run: launch architect-integrator after contributors",
  "  --include-spec-pack    For clean: also remove spec-package/<business>/<module>",
  "  --json                 Print machine-readable output",
  "  --help                 Show this help message",
].join("\n");

export const KM_PAGE_ANALYSIS_HELP_TEXT = [
  "Usage: harness km-page-analysis <prepare|run|validate|status|clean> [options]",
  "",
  "Prepare and operate a page-level module dependency analysis workflow.",
  "",
  "Commands:",
  "  prepare  Create run artifacts and an architect prompt",
  "  run      Prepare, launch the architect agent, then validate outputs",
  "  validate Check page-analysis.md and module-dependency.yaml output shape",
  "  status   Print run status and output presence",
  "  clean    Remove run artifacts; pass --include-output to remove page-analysis outputs",
  "",
  "Options:",
  "  --harness-repo <path>  Target harness repository; defaults to cwd",
  "  --business <id>        Business id, for example shop",
  "  --page <id>            Page id, for example shoppage",
  "  --source <id=path>     Source repo path; can be passed multiple times",
  "  --source-path <id=path> Source subpath inside a named source repo",
  "  --source-platform <id=name> Optional source platform label",
  "  --target <id=path>     Target repo path; id distinguishes android, ios, frontend, backend, etc.",
  "  --target-platform <id=name> Optional target platform label; defaults to id",
  "  --machpro-repo <path>  Deprecated alias for --source machpro=<path>",
  "  --machpro-path <path>  Deprecated alias for --source-path machpro=<path>",
  "  --android-repo <path>  Deprecated alias for --target android=<path>",
  "  --ios-repo <path>      Deprecated alias for --target ios=<path>",
  "  --known-module <id>    Known module id; can be passed multiple times",
  "  --known-modules <list> Comma-separated known module ids",
  "  --run-id <id>          Stable run id; prepare/run default to timestamp",
  "  --force                Replace an existing run or page-analysis output files",
  "  --agent-command-template <cmd>  Shell template using {agent}, {prompt_file}, {run_dir}, {harness_repo}, {business}, {page}, {output_dir}",
  "  --include-output       For clean: also remove page-analysis.md and module-dependency.yaml",
  "  --json                 Print machine-readable output",
  "  --help                 Show this help message",
].join("\n");
