import { access, mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import YAML from "yaml";
import { describe, expect, it } from "vitest";

import { adaptersCapabilitiesReportSchema, loadManifest } from "@harness/core";

import { runCli } from "../src/index.js";

function createIo() {
  const stdout: string[] = [];
  const stderr: string[] = [];

  return {
    io: {
      stdout(message: string): void {
        stdout.push(message);
      },
      stderr(message: string): void {
        stderr.push(message);
      }
    },
    stdout,
    stderr
  };
}

async function withCwd<T>(cwd: string, callback: () => Promise<T>): Promise<T> {
  const previousCwd = process.cwd();
  process.chdir(cwd);

  try {
    return await callback();
  } finally {
    process.chdir(previousCwd);
  }
}

async function createWorkspace(tempRoot: string): Promise<string> {
  const workspaceDir = path.join(tempRoot, "demo");

  await withCwd(tempRoot, async () => {
    const initIo = createIo();
    expect(await runCli(["init", "demo"], initIo.io)).toBe(0);
  });

  return workspaceDir;
}

async function updateClaudeConfig(
  workspaceDir: string,
  tools: string[],
  claudeConfig: {
    agentsSource?: string;
    commandsSource?: string;
  } = {}
): Promise<void> {
  const harnessPath = path.join(workspaceDir, "harness.yaml");
  const source = await readFile(harnessPath, "utf8");
  const document = YAML.parse(source) as Record<string, unknown>;

  document.tools = tools;
  document.adapters = Object.fromEntries(
    tools.map((tool) => [
      tool,
      {
        enabled: true,
        target: ".",
        ...(tool === "claude-code" && claudeConfig.agentsSource ? { agents_source: claudeConfig.agentsSource } : {}),
        ...(tool === "claude-code" && claudeConfig.commandsSource ? { commands_source: claudeConfig.commandsSource } : {})
      }
    ])
  );

  await writeFile(harnessPath, YAML.stringify(document), "utf8");
}

async function seedClaudeSources(workspaceDir: string): Promise<void> {
  await mkdir(path.join(workspaceDir, "claude", "agents"), { recursive: true });
  await mkdir(path.join(workspaceDir, "claude", "commands"), { recursive: true });
  await writeFile(
    path.join(workspaceDir, "claude", "agents", "code-reviewer.md"),
    "---\ndescription: Senior reviewer\ntools: [Read, Grep]\n---\nYou review code carefully.\n",
    "utf8"
  );
  await writeFile(path.join(workspaceDir, "claude", "agents", "planner.md"), "You plan things.\n", "utf8");
  await writeFile(path.join(workspaceDir, "claude", "commands", "review.md"), "---\ndescription: Run review\n---\nReview now.\n", "utf8");
  await writeFile(path.join(workspaceDir, "claude", "commands", "summarize.md"), "Summarize now.\n", "utf8");
}

describe.sequential("claude-code subdirectory integration", () => {
  it("syncs multiple agents and commands while preserving frontmatter and body content", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-subdirs-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await seedClaudeSources(workspaceDir);
    await updateClaudeConfig(workspaceDir, ["claude-code"]);

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}")).toEqual({
        added: [
          { path: ".claude/agents/code-reviewer.md", reason: "new" },
          { path: ".claude/agents/planner.md", reason: "new" },
          { path: ".claude/commands/review.md", reason: "new" },
          { path: ".claude/commands/summarize.md", reason: "new" },
          { path: "CLAUDE.md", reason: "new" }
        ],
        modified: [],
        removed: [],
        unchanged: []
      });

      const reviewer = await readFile(path.join(workspaceDir, ".claude", "agents", "code-reviewer.md"), "utf8");
      const planner = await readFile(path.join(workspaceDir, ".claude", "agents", "planner.md"), "utf8");
      const reviewCommand = await readFile(path.join(workspaceDir, ".claude", "commands", "review.md"), "utf8");
      const summarizeCommand = await readFile(path.join(workspaceDir, ".claude", "commands", "summarize.md"), "utf8");

      expect(reviewer).toContain("---\ndescription: Senior reviewer\ntools: [Read, Grep]\n---\n<!-- generated by harness; do not edit. Source: claude/agents/code-reviewer.md -->\nYou review code carefully.\n");
      expect(planner.startsWith("<!-- generated by harness; do not edit. Source: claude/agents/planner.md -->\n")).toBe(true);
      expect(reviewCommand).toContain("---\ndescription: Run review\n---\n<!-- generated by harness; do not edit. Source: claude/commands/review.md -->\nReview now.\n");
      expect(summarizeCommand.startsWith("<!-- generated by harness; do not edit. Source: claude/commands/summarize.md -->\n")).toBe(true);

      const manifest = await loadManifest(workspaceDir);
      expect(manifest.files.map((file) => file.path)).toEqual([
        ".claude/agents/code-reviewer.md",
        ".claude/agents/planner.md",
        ".claude/commands/review.md",
        ".claude/commands/summarize.md",
        "CLAUDE.md"
      ]);

      const diffIo = createIo();
      expect(await runCli(["diff", "--json"], diffIo.io)).toBe(0);
      expect(JSON.parse(diffIo.stdout[0] ?? "{}")).toEqual({
        added: [],
        modified: [],
        removed: [],
        unchanged: [
          { path: ".claude/agents/code-reviewer.md", reason: "sha256-match" },
          { path: ".claude/agents/planner.md", reason: "sha256-match" },
          { path: ".claude/commands/review.md", reason: "sha256-match" },
          { path: ".claude/commands/summarize.md", reason: "sha256-match" },
          { path: "CLAUDE.md", reason: "sha256-match" }
        ]
      });
    });
  });

  it("removes a generated agent file when its source markdown is deleted", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-remove-agent-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await seedClaudeSources(workspaceDir);
    await updateClaudeConfig(workspaceDir, ["claude-code"]);

    await withCwd(workspaceDir, async () => {
      const initialSync = createIo();
      expect(await runCli(["sync"], initialSync.io)).toBe(0);
    });

    await rm(path.join(workspaceDir, "claude", "agents", "planner.md"));

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}")).toEqual({
        added: [],
        modified: [],
        removed: [{ path: ".claude/agents/planner.md", reason: "manifest-owned-not-planned" }],
        unchanged: [
          { path: ".claude/agents/code-reviewer.md", reason: "sha256-match" },
          { path: ".claude/commands/review.md", reason: "sha256-match" },
          { path: ".claude/commands/summarize.md", reason: "sha256-match" },
          { path: "CLAUDE.md", reason: "sha256-match" }
        ]
      });

      await expect(access(path.join(workspaceDir, ".claude", "agents", "planner.md"))).rejects.toMatchObject({ code: "ENOENT" });

      const diffIo = createIo();
      expect(await runCli(["diff", "--json"], diffIo.io)).toBe(0);
      expect(JSON.parse(diffIo.stdout[0] ?? "{}")).toEqual({
        added: [],
        modified: [],
        removed: [],
        unchanged: [
          { path: ".claude/agents/code-reviewer.md", reason: "sha256-match" },
          { path: ".claude/commands/review.md", reason: "sha256-match" },
          { path: ".claude/commands/summarize.md", reason: "sha256-match" },
          { path: "CLAUDE.md", reason: "sha256-match" }
        ]
      });
    });
  });

  it("cleans all claude-code-managed files when the adapter is disabled", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-disable-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await seedClaudeSources(workspaceDir);
    await updateClaudeConfig(workspaceDir, ["claude-code"]);

    await withCwd(workspaceDir, async () => {
      const initialSync = createIo();
      expect(await runCli(["sync"], initialSync.io)).toBe(0);
    });

    await updateClaudeConfig(workspaceDir, []);

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);

      const result = JSON.parse(syncIo.stdout[0] ?? "{}") as {
        added: unknown[];
        modified: unknown[];
        removed: Array<{ path: string; reason: string }>;
        unchanged: unknown[];
      };

      expect(result.added).toEqual([]);
      expect(result.modified).toEqual([]);
      expect(result.unchanged).toEqual([]);
      expect(result.removed).toEqual([
        { path: ".claude/agents/code-reviewer.md", reason: "manifest-owned-not-planned" },
        { path: ".claude/agents/planner.md", reason: "manifest-owned-not-planned" },
        { path: ".claude/commands/review.md", reason: "manifest-owned-not-planned" },
        { path: ".claude/commands/summarize.md", reason: "manifest-owned-not-planned" },
        { path: "CLAUDE.md", reason: "manifest-owned-not-planned" }
      ]);

      await expect(access(path.join(workspaceDir, ".claude", "agents", "code-reviewer.md"))).rejects.toMatchObject({
        code: "ENOENT"
      });
      await expect(access(path.join(workspaceDir, ".claude", "commands", "review.md"))).rejects.toMatchObject({
        code: "ENOENT"
      });
      await expect(access(path.join(workspaceDir, "CLAUDE.md"))).rejects.toMatchObject({ code: "ENOENT" });

      const manifest = await loadManifest(workspaceDir);
      expect(manifest.files).toEqual([]);
    });
  });

  it("keeps capabilities add-only while claude-code grows agents and commands support", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-capabilities-"));

    await withCwd(tempRoot, async () => {
      const capabilitiesIo = createIo();
      expect(await runCli(["adapters", "capabilities", "--json"], capabilitiesIo.io)).toBe(0);

      const report = adaptersCapabilitiesReportSchema.parse(JSON.parse(capabilitiesIo.stdout[0] ?? "{}"));
      expect(report.schema_version).toBe(1);
      expect(report.adapters).toEqual([
        {
          id: "claude-code",
          features: ["claude-agents-md", "claude-commands-md", "claude-docs", "claude-hooks", "claude-mcp", "claude-md", "claude-metrics", "claude-plugins", "claude-reference-projects", "claude-rules-md", "claude-scripts", "claude-skills"]
        },
        {
          id: "codex",
          features: ["agents-md", "codex-config-toml"]
        },
        {
          id: "cursor",
          features: ["cursor-mcp-json", "cursor-rules-mdc"]
        }
      ]);
    });
  });

  it("skips missing source directories without failing", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-missing-sources-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await updateClaudeConfig(workspaceDir, ["claude-code"], {
      agentsSource: "./missing-agents",
      commandsSource: "./missing-commands"
    });

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(syncIo.stderr).toEqual([]);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}")).toEqual({
        added: [{ path: "CLAUDE.md", reason: "new" }],
        modified: [],
        removed: [],
        unchanged: []
      });
    });
  });

  it("warns and ignores nested markdown files under claude source directories", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-nested-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await mkdir(path.join(workspaceDir, "claude", "agents", "nested"), { recursive: true });
    await updateClaudeConfig(workspaceDir, ["claude-code"]);
    await writeFile(path.join(workspaceDir, "claude", "agents", "nested", "inner.md"), "Nested agent.\n", "utf8");

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(syncIo.stderr).toEqual(["Warning: claude-code adapter ignoring nested file: claude/agents/nested/inner.md"]);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}")).toEqual({
        added: [{ path: "CLAUDE.md", reason: "new" }],
        modified: [],
        removed: [],
        unchanged: []
      });

      const manifest = await loadManifest(workspaceDir);
      expect(manifest.files.map((file) => file.path)).toEqual(["CLAUDE.md"]);
    });
  });
});
