import { access, mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import YAML from "yaml";
import { describe, expect, it } from "vitest";

import { runCli } from "../src/index.js";

function createIo() {
  const stdout: string[] = [];
  const stderr: string[] = [];

  return {
    io: {
      stdout(message: string): void {
        stdout.push(message);
      },
      stderr(message: string): void {
        stderr.push(message);
      }
    },
    stdout,
    stderr
  };
}

async function withCwd<T>(cwd: string, callback: () => Promise<T>): Promise<T> {
  const previousCwd = process.cwd();
  process.chdir(cwd);

  try {
    return await callback();
  } finally {
    process.chdir(previousCwd);
  }
}

async function createWorkspace(tempRoot: string): Promise<string> {
  const workspaceDir = path.join(tempRoot, "demo");

  await withCwd(tempRoot, async () => {
    const initIo = createIo();
    expect(await runCli(["init", "demo"], initIo.io)).toBe(0);
  });

  return workspaceDir;
}

async function updateClaudeConfig(workspaceDir: string, tools: string[], rulesSource = "./claude/rules"): Promise<void> {
  const harnessPath = path.join(workspaceDir, "harness.yaml");
  const source = await readFile(harnessPath, "utf8");
  const document = YAML.parse(source) as Record<string, unknown>;

  document.tools = tools;
  document.adapters = Object.fromEntries(
    tools.map((tool) => [
      tool,
      {
        enabled: true,
        target: ".",
        ...(tool === "claude-code" ? { rules_source: rulesSource } : {})
      }
    ])
  );

  await writeFile(harnessPath, YAML.stringify(document), "utf8");
}

describe.sequential("claude rules integration", () => {
  it("renders top-level markdown rules into .claude/rules", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-rules-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await mkdir(path.join(workspaceDir, "claude", "rules"), { recursive: true });
    await writeFile(path.join(workspaceDir, "claude", "rules", "style.md"), "rule body\n", "utf8");
    await updateClaudeConfig(workspaceDir, ["claude-code"]);

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}")).toEqual({
        added: [
          { path: ".claude/rules/style.md", reason: "new" },
          { path: "CLAUDE.md", reason: "new" }
        ],
        modified: [],
        removed: [],
        unchanged: []
      });

      const renderedRule = await readFile(path.join(workspaceDir, ".claude", "rules", "style.md"), "utf8");
      expect(renderedRule).toBe("<!-- generated by harness; do not edit. Source: claude/rules/style.md -->\nrule body\n");

      const diffIo = createIo();
      expect(await runCli(["diff", "--check"], diffIo.io)).toBe(0);
    });
  });

  it("cleans a generated rule when its source file is removed", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-rules-remove-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await mkdir(path.join(workspaceDir, "claude", "rules"), { recursive: true });
    await writeFile(path.join(workspaceDir, "claude", "rules", "style.md"), "rule body\n", "utf8");
    await updateClaudeConfig(workspaceDir, ["claude-code"]);

    await withCwd(workspaceDir, async () => {
      const initialSync = createIo();
      expect(await runCli(["sync"], initialSync.io)).toBe(0);
    });

    await rm(path.join(workspaceDir, "claude", "rules", "style.md"));

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}")).toEqual({
        added: [],
        modified: [],
        removed: [{ path: ".claude/rules/style.md", reason: "manifest-owned-not-planned" }],
        unchanged: [{ path: "CLAUDE.md", reason: "sha256-match" }]
      });

      await expect(access(path.join(workspaceDir, ".claude", "rules", "style.md"))).rejects.toMatchObject({ code: "ENOENT" });
    });
  });
});
