import { access, chmod, mkdtemp, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import YAML from "yaml";
import { describe, expect, it } from "vitest";

import { adaptersCapabilitiesReportSchema, loadManifest } from "@harness/core";

import { runCli } from "../src/index.js";

function createIo() {
  const stdout: string[] = [];
  const stderr: string[] = [];

  return {
    io: {
      stdout(message: string): void {
        stdout.push(message);
      },
      stderr(message: string): void {
        stderr.push(message);
      }
    },
    stdout,
    stderr
  };
}

async function withCwd<T>(cwd: string, callback: () => Promise<T>): Promise<T> {
  const previousCwd = process.cwd();
  process.chdir(cwd);

  try {
    return await callback();
  } finally {
    process.chdir(previousCwd);
  }
}

async function createWorkspace(tempRoot: string): Promise<string> {
  const workspaceDir = path.join(tempRoot, "demo");

  await withCwd(tempRoot, async () => {
    const initIo = createIo();
    expect(await runCli(["init", "demo"], initIo.io)).toBe(0);
  });

  return workspaceDir;
}

async function updateClaudeConfig(
  workspaceDir: string,
  tools: string[],
  claudeConfig: {
    scriptsSource?: string;
  } = {}
): Promise<void> {
  const harnessPath = path.join(workspaceDir, "harness.yaml");
  const source = await readFile(harnessPath, "utf8");
  const document = YAML.parse(source) as Record<string, unknown>;

  document.tools = tools;
  document.adapters = Object.fromEntries(
    tools.map((tool) => [
      tool,
      {
        enabled: true,
        target: ".",
        ...(tool === "claude-code" && claudeConfig.scriptsSource ? { scripts_source: claudeConfig.scriptsSource } : {})
      }
    ])
  );

  await writeFile(harnessPath, YAML.stringify(document), "utf8");
}

async function seedScriptWorkspace(workspaceDir: string): Promise<void> {
  await mkdir(path.join(workspaceDir, "claude", "scripts", "metrics"), { recursive: true });
  await writeFile(path.join(workspaceDir, "claude", "scripts", "session-start-check.sh"), "#!/usr/bin/env bash\necho session\n", "utf8");
  await writeFile(path.join(workspaceDir, "claude", "scripts", "post-commit-check.sh"), "#!/usr/bin/env bash\necho commit\n", "utf8");
  await writeFile(path.join(workspaceDir, "claude", "scripts", "task-completed-check.sh"), "#!/usr/bin/env bash\necho task\n", "utf8");
  await writeFile(path.join(workspaceDir, "claude", "scripts", "mvvm-lint.sh"), "#!/usr/bin/env bash\necho lint\n", "utf8");
  await writeFile(path.join(workspaceDir, "claude", "scripts", "metrics", "template.md"), "metric template\n", "utf8");
  await chmod(path.join(workspaceDir, "claude", "scripts", "session-start-check.sh"), 0o755);
  await chmod(path.join(workspaceDir, "claude", "scripts", "post-commit-check.sh"), 0o755);
  await chmod(path.join(workspaceDir, "claude", "scripts", "task-completed-check.sh"), 0o755);
  await chmod(path.join(workspaceDir, "claude", "scripts", "mvvm-lint.sh"), 0o755);
}

function sortPaths(paths: readonly string[]): string[] {
  return [...paths].sort((left, right) => left.localeCompare(right));
}

describe.sequential("claude scripts integration", () => {
  it("syncs a sailor-like scripts tree with executable modes and markdown markers", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-scripts-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await seedScriptWorkspace(workspaceDir);
    await updateClaudeConfig(workspaceDir, ["claude-code"], { scriptsSource: "./claude/scripts" });

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);

      const result = JSON.parse(syncIo.stdout[0] ?? "{}") as {
        added: Array<{ path: string; reason: string }>;
      };
      expect(result.added).toEqual(
        sortPaths([
          ".claude/scripts/metrics/template.md",
          ".claude/scripts/mvvm-lint.sh",
          ".claude/scripts/post-commit-check.sh",
          ".claude/scripts/session-start-check.sh",
          ".claude/scripts/task-completed-check.sh",
          "CLAUDE.md"
        ]).map((entry) => ({ path: entry, reason: "new" }))
      );

      const sessionScript = await readFile(path.join(workspaceDir, ".claude", "scripts", "session-start-check.sh"), "utf8");
      const templateDocument = await readFile(path.join(workspaceDir, ".claude", "scripts", "metrics", "template.md"), "utf8");
      const scriptMode = (await stat(path.join(workspaceDir, ".claude", "scripts", "session-start-check.sh"))).mode & 0o777;

      expect(sessionScript).toBe("#!/usr/bin/env bash\necho session\n");
      expect(templateDocument).toBe("<!-- generated by harness; do not edit. Source: claude/scripts/metrics/template.md -->\nmetric template\n");
      expect(scriptMode).toBe(0o755);

      const manifest = await loadManifest(workspaceDir);
      expect(sortPaths(manifest.files.map((file) => file.path))).toEqual(sortPaths([
        ".claude/scripts/metrics/template.md",
        ".claude/scripts/mvvm-lint.sh",
        ".claude/scripts/post-commit-check.sh",
        ".claude/scripts/session-start-check.sh",
        ".claude/scripts/task-completed-check.sh",
        "CLAUDE.md"
      ]));

      const diffIo = createIo();
      expect(await runCli(["diff", "--check"], diffIo.io)).toBe(0);
    });
  });

  it("removes one generated script when its source file is deleted", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-scripts-remove-file-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await seedScriptWorkspace(workspaceDir);
    await updateClaudeConfig(workspaceDir, ["claude-code"], { scriptsSource: "./claude/scripts" });

    await withCwd(workspaceDir, async () => {
      const initialSync = createIo();
      expect(await runCli(["sync"], initialSync.io)).toBe(0);
    });

    await rm(path.join(workspaceDir, "claude", "scripts", "mvvm-lint.sh"));

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}").removed).toEqual([
        { path: ".claude/scripts/mvvm-lint.sh", reason: "manifest-owned-not-planned" }
      ]);
      await expect(access(path.join(workspaceDir, ".claude", "scripts", "mvvm-lint.sh"))).rejects.toMatchObject({
        code: "ENOENT"
      });
    });
  });

  it("cleans all generated claude scripts when claude-code is disabled", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-scripts-disable-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await seedScriptWorkspace(workspaceDir);
    await updateClaudeConfig(workspaceDir, ["claude-code"], { scriptsSource: "./claude/scripts" });

    await withCwd(workspaceDir, async () => {
      const initialSync = createIo();
      expect(await runCli(["sync"], initialSync.io)).toBe(0);
    });

    await updateClaudeConfig(workspaceDir, []);

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);

      const removedPaths = sortPaths(JSON.parse(syncIo.stdout[0] ?? "{}").removed.map((entry: { path: string }) => entry.path));
      expect(removedPaths).toEqual(
        sortPaths([
          ".claude/scripts/metrics/template.md",
          ".claude/scripts/mvvm-lint.sh",
          ".claude/scripts/post-commit-check.sh",
          ".claude/scripts/session-start-check.sh",
          ".claude/scripts/task-completed-check.sh",
          "CLAUDE.md"
        ])
      );
    });
  });

  it("keeps capabilities add-only while adding claude scripts support", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-scripts-capabilities-"));

    await withCwd(tempRoot, async () => {
      const capabilitiesIo = createIo();
      expect(await runCli(["adapters", "capabilities", "--json"], capabilitiesIo.io)).toBe(0);

      const report = adaptersCapabilitiesReportSchema.parse(JSON.parse(capabilitiesIo.stdout[0] ?? "{}"));
      expect(report.schema_version).toBe(1);
      expect(report.adapters).toEqual([
        {
          id: "claude-code",
          features: [
            "claude-agents-md",
            "claude-commands-md",
            "claude-docs",
            "claude-hooks",
            "claude-mcp",
            "claude-md",
            "claude-metrics",
            "claude-plugins",
            "claude-reference-projects",
            "claude-rules-md",
            "claude-scripts",
            "claude-skills"
          ]
        },
        {
          id: "codex",
          features: ["agents-md", "codex-config-toml"]
        },
        {
          id: "cursor",
          features: ["cursor-mcp-json", "cursor-rules-mdc"]
        }
      ]);
    });
  });
});
