import { access, chmod, mkdtemp, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import YAML from "yaml";
import { describe, expect, it } from "vitest";

import { adaptersCapabilitiesReportSchema, loadManifest } from "@harness/core";

import { runCli } from "../src/index.js";

function createIo() {
  const stdout: string[] = [];
  const stderr: string[] = [];

  return {
    io: {
      stdout(message: string): void {
        stdout.push(message);
      },
      stderr(message: string): void {
        stderr.push(message);
      }
    },
    stdout,
    stderr
  };
}

async function withCwd<T>(cwd: string, callback: () => Promise<T>): Promise<T> {
  const previousCwd = process.cwd();
  process.chdir(cwd);

  try {
    return await callback();
  } finally {
    process.chdir(previousCwd);
  }
}

async function createWorkspace(tempRoot: string): Promise<string> {
  const workspaceDir = path.join(tempRoot, "demo");

  await withCwd(tempRoot, async () => {
    const initIo = createIo();
    expect(await runCli(["init", "demo"], initIo.io)).toBe(0);
  });

  return workspaceDir;
}

async function updateClaudeConfig(
  workspaceDir: string,
  tools: string[],
  claudeConfig: {
    skillsSource?: string;
  } = {}
): Promise<void> {
  const harnessPath = path.join(workspaceDir, "harness.yaml");
  const source = await readFile(harnessPath, "utf8");
  const document = YAML.parse(source) as Record<string, unknown>;

  document.tools = tools;
  document.adapters = Object.fromEntries(
    tools.map((tool) => [
      tool,
      {
        enabled: true,
        target: ".",
        ...(tool === "claude-code" && claudeConfig.skillsSource ? { skills_source: claudeConfig.skillsSource } : {})
      }
    ])
  );

  await writeFile(harnessPath, YAML.stringify(document), "utf8");
}

async function seedSkillWorkspace(workspaceDir: string): Promise<void> {
  await mkdir(path.join(workspaceDir, "claude", "skills", "code-review", "resources"), { recursive: true });
  await mkdir(path.join(workspaceDir, "claude", "skills", "code-review", "scripts"), { recursive: true });
  await writeFile(
    path.join(workspaceDir, "claude", "skills", "code-review", "SKILL.md"),
    "---\nname: code-review\n---\nRun code review.\n",
    "utf8"
  );
  await writeFile(path.join(workspaceDir, "claude", "skills", "code-review", "resources", "checklist.md"), "checklist body\n", "utf8");
  await writeFile(path.join(workspaceDir, "claude", "skills", "code-review", "scripts", "analyze.sh"), "#!/usr/bin/env bash\necho analyze\n", "utf8");
  await chmod(path.join(workspaceDir, "claude", "skills", "code-review", "scripts", "analyze.sh"), 0o755);
}

function sortPaths(paths: readonly string[]): string[] {
  return [...paths].sort((left, right) => left.localeCompare(right));
}

describe.sequential("claude skills integration", () => {
  it("syncs a skill tree with markdown markers and executable mode preservation", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-skills-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await seedSkillWorkspace(workspaceDir);
    await updateClaudeConfig(workspaceDir, ["claude-code"], { skillsSource: "./claude/skills" });

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);

      const result = JSON.parse(syncIo.stdout[0] ?? "{}") as {
        added: Array<{ path: string; reason: string }>;
      };
      expect(result.added).toEqual(
        sortPaths([
          ".claude/skills/code-review/SKILL.md",
          ".claude/skills/code-review/resources/checklist.md",
          ".claude/skills/code-review/scripts/analyze.sh",
          "CLAUDE.md"
        ]).map((entry) => ({ path: entry, reason: "new" }))
      );

      const skillDocument = await readFile(path.join(workspaceDir, ".claude", "skills", "code-review", "SKILL.md"), "utf8");
      const checklistDocument = await readFile(path.join(workspaceDir, ".claude", "skills", "code-review", "resources", "checklist.md"), "utf8");
      const scriptDocument = await readFile(path.join(workspaceDir, ".claude", "skills", "code-review", "scripts", "analyze.sh"), "utf8");
      const scriptMode = (await stat(path.join(workspaceDir, ".claude", "skills", "code-review", "scripts", "analyze.sh"))).mode & 0o777;

      expect(skillDocument).toContain("---\nname: code-review\n---\n<!-- generated by harness; do not edit. Source: claude/skills/code-review/SKILL.md -->\nRun code review.\n");
      expect(checklistDocument.startsWith("<!-- generated by harness; do not edit. Source: claude/skills/code-review/resources/checklist.md -->\n")).toBe(true);
      expect(scriptDocument).toBe("#!/usr/bin/env bash\necho analyze\n");
      expect(scriptMode).toBe(0o755);

      const manifest = await loadManifest(workspaceDir);
      expect(sortPaths(manifest.files.map((file) => file.path))).toEqual(sortPaths([
        ".claude/skills/code-review/resources/checklist.md",
        ".claude/skills/code-review/scripts/analyze.sh",
        ".claude/skills/code-review/SKILL.md",
        "CLAUDE.md"
      ]));

      const diffIo = createIo();
      expect(await runCli(["diff", "--check"], diffIo.io)).toBe(0);
    });
  });

  it("removes one generated skill asset when its source file is deleted", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-skills-remove-file-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await seedSkillWorkspace(workspaceDir);
    await updateClaudeConfig(workspaceDir, ["claude-code"], { skillsSource: "./claude/skills" });

    await withCwd(workspaceDir, async () => {
      const initialSync = createIo();
      expect(await runCli(["sync"], initialSync.io)).toBe(0);
    });

    await rm(path.join(workspaceDir, "claude", "skills", "code-review", "resources", "checklist.md"));

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}").removed).toEqual([
        { path: ".claude/skills/code-review/resources/checklist.md", reason: "manifest-owned-not-planned" }
      ]);
      await expect(access(path.join(workspaceDir, ".claude", "skills", "code-review", "resources", "checklist.md"))).rejects.toMatchObject({
        code: "ENOENT"
      });

      const diffIo = createIo();
      expect(await runCli(["diff", "--check"], diffIo.io)).toBe(0);
    });
  });

  it("cleans an entire generated skill tree when the source directory is removed", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-skills-remove-dir-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await seedSkillWorkspace(workspaceDir);
    await updateClaudeConfig(workspaceDir, ["claude-code"], { skillsSource: "./claude/skills" });

    await withCwd(workspaceDir, async () => {
      const initialSync = createIo();
      expect(await runCli(["sync"], initialSync.io)).toBe(0);
    });

    await rm(path.join(workspaceDir, "claude", "skills", "code-review"), { recursive: true, force: true });

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(sortPaths(JSON.parse(syncIo.stdout[0] ?? "{}").removed.map((entry: { path: string }) => entry.path))).toEqual(
        sortPaths([
          ".claude/skills/code-review/SKILL.md",
          ".claude/skills/code-review/resources/checklist.md",
          ".claude/skills/code-review/scripts/analyze.sh"
        ])
      );
    });
  });

  it("cleans all claude-code-managed outputs when the adapter is disabled", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-skills-disable-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await seedSkillWorkspace(workspaceDir);
    await updateClaudeConfig(workspaceDir, ["claude-code"], { skillsSource: "./claude/skills" });

    await withCwd(workspaceDir, async () => {
      const initialSync = createIo();
      expect(await runCli(["sync"], initialSync.io)).toBe(0);
    });

    await updateClaudeConfig(workspaceDir, []);

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);

      const removedPaths = sortPaths(JSON.parse(syncIo.stdout[0] ?? "{}").removed.map((entry: { path: string }) => entry.path));
      expect(removedPaths).toEqual(
        sortPaths([
          ".claude/skills/code-review/SKILL.md",
          ".claude/skills/code-review/resources/checklist.md",
          ".claude/skills/code-review/scripts/analyze.sh",
          "CLAUDE.md"
        ])
      );
    });
  });

  it("keeps capabilities add-only while adding claude skills support", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-skills-capabilities-"));

    await withCwd(tempRoot, async () => {
      const capabilitiesIo = createIo();
      expect(await runCli(["adapters", "capabilities", "--json"], capabilitiesIo.io)).toBe(0);

      const report = adaptersCapabilitiesReportSchema.parse(JSON.parse(capabilitiesIo.stdout[0] ?? "{}"));
      expect(report.schema_version).toBe(1);
      expect(report.adapters).toEqual([
        {
          id: "claude-code",
          features: ["claude-agents-md", "claude-commands-md", "claude-docs", "claude-hooks", "claude-mcp", "claude-md", "claude-metrics", "claude-plugins", "claude-reference-projects", "claude-rules-md", "claude-scripts", "claude-skills"]
        },
        {
          id: "codex",
          features: ["agents-md", "codex-config-toml"]
        },
        {
          id: "cursor",
          features: ["cursor-mcp-json", "cursor-rules-mdc"]
        }
      ]);
    });
  });

  it("tolerates missing or empty skills sources and skips hidden skill directories", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-skills-tolerance-"));
    const workspaceDir = await createWorkspace(tempRoot);
    await updateClaudeConfig(workspaceDir, ["claude-code"], { skillsSource: "./missing-skills" });

    await withCwd(workspaceDir, async () => {
      const missingSync = createIo();
      expect(await runCli(["sync", "--json"], missingSync.io)).toBe(0);
      expect(JSON.parse(missingSync.stdout[0] ?? "{}")).toEqual({
        added: [{ path: "CLAUDE.md", reason: "new" }],
        modified: [],
        removed: [],
        unchanged: []
      });
    });

    await mkdir(path.join(workspaceDir, "claude", "skills"), { recursive: true });
    await updateClaudeConfig(workspaceDir, ["claude-code"], { skillsSource: "./claude/skills" });

    await withCwd(workspaceDir, async () => {
      const emptySync = createIo();
      expect(await runCli(["sync", "--json"], emptySync.io)).toBe(0);
      expect(emptySync.stderr).toEqual([]);
      expect(JSON.parse(emptySync.stdout[0] ?? "{}")).toEqual({
        added: [],
        modified: [],
        removed: [],
        unchanged: [{ path: "CLAUDE.md", reason: "sha256-match" }]
      });
    });

    await mkdir(path.join(workspaceDir, "claude", "skills", ".hidden-skill"), { recursive: true });
    await writeFile(path.join(workspaceDir, "claude", "skills", ".hidden-skill", "SKILL.md"), "hidden\n", "utf8");

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(syncIo.stderr).toEqual([]);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}")).toEqual({
        added: [],
        modified: [],
        removed: [],
        unchanged: [{ path: "CLAUDE.md", reason: "sha256-match" }]
      });
    });
  });
});
