import { execFile } from "node:child_process";
import { mkdtemp, readFile, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";

import YAML from "yaml";
import { describe, expect, it } from "vitest";

import { loadManifest } from "@harness/core";

import { runCli } from "../src/index.js";

const execFileAsync = promisify(execFile);

function createIo() {
  const stdout: string[] = [];
  const stderr: string[] = [];

  return {
    io: {
      stdout(message: string): void {
        stdout.push(message);
      },
      stderr(message: string): void {
        stderr.push(message);
      }
    },
    stdout,
    stderr
  };
}

async function withCwd<T>(cwd: string, callback: () => Promise<T>): Promise<T> {
  const previousCwd = process.cwd();
  process.chdir(cwd);

  try {
    return await callback();
  } finally {
    process.chdir(previousCwd);
  }
}

async function updatePreCommitHook(
  workspaceDir: string,
  hookConfig:
    | {
        enabled?: boolean;
        run: string;
      }
    | null
): Promise<void> {
  const harnessPath = path.join(workspaceDir, "harness.yaml");
  const source = await readFile(harnessPath, "utf8");
  const document = YAML.parse(source) as Record<string, unknown>;

  if (!document.hooks || typeof document.hooks !== "object") {
    document.hooks = {};
  }

  const hooks = document.hooks as Record<string, unknown>;
  if (hookConfig) {
    hooks["pre-commit"] = hookConfig;
  } else {
    delete hooks["pre-commit"];
  }

  await writeFile(harnessPath, YAML.stringify(document), "utf8");
}

async function createWorkspace(tempRoot: string): Promise<string> {
  const workspaceDir = path.join(tempRoot, "demo");

  await withCwd(tempRoot, async () => {
    const initIo = createIo();
    expect(await runCli(["init", "demo"], initIo.io)).toBe(0);
  });

  return workspaceDir;
}

describe.sequential("hook sync integration", () => {
  it("syncs a pre-commit hook into .git/hooks with executable mode", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-hook-sync-"));
    const workspaceDir = await createWorkspace(tempRoot);
    const hookPath = path.join(workspaceDir, ".git", "hooks", "pre-commit");

    await execFileAsync("git", ["init", "-q"], { cwd: workspaceDir });
    await updatePreCommitHook(workspaceDir, { run: "echo hi" });

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}")).toEqual({
        added: [
          { path: ".codex/config.toml", reason: "new" },
          { path: ".git/hooks/pre-commit", reason: "new" },
          { path: "AGENTS.md", reason: "new" }
        ],
        modified: [],
        removed: [],
        unchanged: []
      });
    });

    const hookStat = await stat(hookPath);
    const hookContent = await readFile(hookPath, "utf8");

    expect(hookStat.mode & 0o111).not.toBe(0);
    expect(hookContent).toContain("#!/usr/bin/env bash");
    expect(hookContent).toContain("# generated by harness; do not edit");
    expect(hookContent).toContain("echo hi");
  });

  it("detects hook drift, makes `diff --check` fail, and heals on sync", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-hook-drift-"));
    const workspaceDir = await createWorkspace(tempRoot);
    const hookPath = path.join(workspaceDir, ".git", "hooks", "pre-commit");

    await execFileAsync("git", ["init", "-q"], { cwd: workspaceDir });
    await updatePreCommitHook(workspaceDir, { run: "echo hi" });

    await withCwd(workspaceDir, async () => {
      const initialSyncIo = createIo();
      expect(await runCli(["sync"], initialSyncIo.io)).toBe(0);
    });

    await writeFile(hookPath, `${await readFile(hookPath, "utf8")}tampered\n`, "utf8");

    await withCwd(workspaceDir, async () => {
      const diffIo = createIo();
      expect(await runCli(["diff", "--json"], diffIo.io)).toBe(0);
      const diffResult = JSON.parse(diffIo.stdout[0] ?? "{}") as {
        modified: Array<{ path: string; reason: string }>;
      };
      expect(diffResult.modified).toEqual([{ path: ".git/hooks/pre-commit", reason: "sha256-mismatch" }]);

      const checkIo = createIo();
      expect(await runCli(["diff", "--check"], checkIo.io)).toBe(1);

      const syncIo = createIo();
      expect(await runCli(["sync"], syncIo.io)).toBe(0);

      const healedCheckIo = createIo();
      expect(await runCli(["diff", "--check"], healedCheckIo.io)).toBe(0);
    });
  });

  it("removes a manifest-owned hook after it is disabled", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-hook-cleanup-"));
    const workspaceDir = await createWorkspace(tempRoot);
    const hookPath = path.join(workspaceDir, ".git", "hooks", "pre-commit");

    await execFileAsync("git", ["init", "-q"], { cwd: workspaceDir });
    await updatePreCommitHook(workspaceDir, { run: "echo hi" });

    await withCwd(workspaceDir, async () => {
      const initialSyncIo = createIo();
      expect(await runCli(["sync"], initialSyncIo.io)).toBe(0);
    });

    await updatePreCommitHook(workspaceDir, { enabled: false, run: "echo hi" });

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}")).toEqual({
        added: [],
        modified: [],
        removed: [{ path: ".git/hooks/pre-commit", reason: "manifest-owned-not-planned" }],
        unchanged: [
          { path: ".codex/config.toml", reason: "sha256-match" },
          { path: "AGENTS.md", reason: "sha256-match" }
        ]
      });
    });

    await expect(stat(hookPath)).rejects.toMatchObject({ code: "ENOENT" });
  });

  it("skips hook installation outside git repositories without failing sync", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-hook-no-git-"));
    const workspaceDir = await createWorkspace(tempRoot);

    await updatePreCommitHook(workspaceDir, { run: "echo hi" });

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(syncIo.stderr.some((line) => line.toLowerCase().includes("not a git repository"))).toBe(true);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}")).toEqual({
        added: [
          { path: ".codex/config.toml", reason: "new" },
          { path: "AGENTS.md", reason: "new" }
        ],
        modified: [],
        removed: [],
        unchanged: []
      });
    });

    const manifest = await loadManifest(workspaceDir);
    expect(manifest.files.map((file) => file.path)).toEqual([".codex/config.toml", "AGENTS.md"]);
  });
});
