import { access, mkdtemp, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import YAML from "yaml";
import { describe, expect, it } from "vitest";

import { adaptersCapabilitiesReportSchema, loadManifest } from "@harness/core";

import { runCli } from "../src/index.js";

function createIo() {
  const stdout: string[] = [];
  const stderr: string[] = [];

  return {
    io: {
      stdout(message: string): void {
        stdout.push(message);
      },
      stderr(message: string): void {
        stderr.push(message);
      }
    },
    stdout,
    stderr
  };
}

async function withCwd<T>(cwd: string, callback: () => Promise<T>): Promise<T> {
  const previousCwd = process.cwd();
  process.chdir(cwd);

  try {
    return await callback();
  } finally {
    process.chdir(previousCwd);
  }
}

function createAdapterConfig(tools: readonly string[]): Record<string, { enabled: true; target: "." }> {
  const adapters: Record<string, { enabled: true; target: "." }> = {};

  for (const tool of tools) {
    adapters[tool] = {
      enabled: true,
      target: "."
    };
  }

  return adapters;
}

function stripGeneratedMarker(source: string): string {
  return source.replace(/^<!-- generated by harness; do not edit -->\r?\n\r?\n?/, "");
}

async function updateHarnessTools(workspaceDir: string, tools: string[]): Promise<void> {
  const harnessPath = path.join(workspaceDir, "harness.yaml");
  const source = await readFile(harnessPath, "utf8");
  const document = YAML.parse(source) as Record<string, unknown>;

  document.tools = tools;
  document.adapters = createAdapterConfig(tools);

  await writeFile(harnessPath, YAML.stringify(document), "utf8");
}

async function createWorkspaceWithTools(tempRoot: string, tools: string[]): Promise<string> {
  const workspaceDir = path.join(tempRoot, "demo");

  await withCwd(tempRoot, async () => {
    const initIo = createIo();
    expect(await runCli(["init", "demo"], initIo.io)).toBe(0);
  });

  await updateHarnessTools(workspaceDir, tools);
  return workspaceDir;
}

describe.sequential("multi-adapter integration", () => {
  it("syncs claude-code, codex, and cursor into a single manifest and diff returns zero drift", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-multi-adapter-"));
    const workspaceDir = await createWorkspaceWithTools(tempRoot, ["claude-code", "codex", "cursor"]);

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}")).toEqual({
        added: [
          { path: ".codex/config.toml", reason: "new" },
          { path: ".cursor/rules/main.mdc", reason: "new" },
          { path: "AGENTS.md", reason: "new" },
          { path: "CLAUDE.md", reason: "new" }
        ],
        modified: [],
        removed: [],
        unchanged: []
      });

      await expect(access(path.join(workspaceDir, ".codex/config.toml"))).resolves.toBeUndefined();
      await expect(access(path.join(workspaceDir, "AGENTS.md"))).resolves.toBeUndefined();
      await expect(access(path.join(workspaceDir, "CLAUDE.md"))).resolves.toBeUndefined();
      await expect(access(path.join(workspaceDir, ".cursor/rules/main.mdc"))).resolves.toBeUndefined();

      const manifest = await loadManifest(workspaceDir);
      const hashes = manifest.files.map((file) => file.sha256);

      expect(manifest.files.map((file) => file.path)).toEqual([
        ".codex/config.toml",
        ".cursor/rules/main.mdc",
        "AGENTS.md",
        "CLAUDE.md"
      ]);
      expect(new Set(hashes).size).toBe(3);

      const diffIo = createIo();
      expect(await runCli(["diff", "--json"], diffIo.io)).toBe(0);
      expect(JSON.parse(diffIo.stdout[0] ?? "{}")).toEqual({
        added: [],
        modified: [],
        removed: [],
        unchanged: [
          { path: ".codex/config.toml", reason: "sha256-match" },
          { path: ".cursor/rules/main.mdc", reason: "sha256-match" },
          { path: "AGENTS.md", reason: "sha256-match" },
          { path: "CLAUDE.md", reason: "sha256-match" }
        ]
      });
    });
  });

  it("removes claude-code-managed files after claude-code is removed from tools", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-disable-claude-code-"));
    const workspaceDir = await createWorkspaceWithTools(tempRoot, ["claude-code", "codex", "cursor"]);

    await withCwd(workspaceDir, async () => {
      const initialSync = createIo();
      expect(await runCli(["sync"], initialSync.io)).toBe(0);
    });

    await updateHarnessTools(workspaceDir, ["codex", "cursor"]);

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      expect(JSON.parse(syncIo.stdout[0] ?? "{}")).toEqual({
        added: [],
        modified: [],
        removed: [{ path: "CLAUDE.md", reason: "manifest-owned-not-planned" }],
        unchanged: [
          { path: ".codex/config.toml", reason: "sha256-match" },
          { path: ".cursor/rules/main.mdc", reason: "sha256-match" },
          { path: "AGENTS.md", reason: "sha256-match" }
        ]
      });

      const manifest = await loadManifest(workspaceDir);
      expect(manifest.files.map((file) => file.path)).toEqual([".codex/config.toml", ".cursor/rules/main.mdc", "AGENTS.md"]);
      await expect(access(path.join(workspaceDir, "CLAUDE.md"))).rejects.toMatchObject({ code: "ENOENT" });

      const diffIo = createIo();
      expect(await runCli(["diff", "--json"], diffIo.io)).toBe(0);
      expect(JSON.parse(diffIo.stdout[0] ?? "{}")).toEqual({
        added: [],
        modified: [],
        removed: [],
        unchanged: [
          { path: ".codex/config.toml", reason: "sha256-match" },
          { path: ".cursor/rules/main.mdc", reason: "sha256-match" },
          { path: "AGENTS.md", reason: "sha256-match" }
        ]
      });
    });
  });

  it("reports and repairs manual drift in cursor-managed output", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-cursor-drift-"));
    const workspaceDir = await createWorkspaceWithTools(tempRoot, ["claude-code", "codex", "cursor"]);
    const cursorRulesPath = path.join(workspaceDir, ".cursor/rules/main.mdc");

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync"], syncIo.io)).toBe(0);
    });

    await writeFile(cursorRulesPath, `${await readFile(cursorRulesPath, "utf8")}manual\n`, "utf8");

    await withCwd(workspaceDir, async () => {
      const diffIo = createIo();
      expect(await runCli(["diff", "--json"], diffIo.io)).toBe(0);
      const diffResult = JSON.parse(diffIo.stdout[0] ?? "{}") as {
        added: unknown[];
        modified: Array<{ path: string; reason: string }>;
        removed: unknown[];
        unchanged: Array<{ path: string; reason: string }>;
      };

      expect(diffResult.modified).toEqual([{ path: ".cursor/rules/main.mdc", reason: "sha256-mismatch" }]);

      const syncIo = createIo();
      expect(await runCli(["sync", "--json"], syncIo.io)).toBe(0);
      const syncResult = JSON.parse(syncIo.stdout[0] ?? "{}") as {
        modified: Array<{ path: string; reason: string }>;
      };
      expect(syncResult.modified).toEqual([{ path: ".cursor/rules/main.mdc", reason: "sha256-mismatch" }]);

      const healedDiffIo = createIo();
      expect(await runCli(["diff", "--json"], healedDiffIo.io)).toBe(0);
      expect(JSON.parse(healedDiffIo.stdout[0] ?? "{}")).toEqual({
        added: [],
        modified: [],
        removed: [],
        unchanged: [
          { path: ".codex/config.toml", reason: "sha256-match" },
          { path: ".cursor/rules/main.mdc", reason: "sha256-match" },
          { path: "AGENTS.md", reason: "sha256-match" },
          { path: "CLAUDE.md", reason: "sha256-match" }
        ]
      });
    });
  });

  it("keeps CLAUDE.md and AGENTS.md aligned because they share the canonical source", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-claude-equals-agents-"));
    const workspaceDir = await createWorkspaceWithTools(tempRoot, ["claude-code", "codex", "cursor"]);

    await withCwd(workspaceDir, async () => {
      const syncIo = createIo();
      expect(await runCli(["sync"], syncIo.io)).toBe(0);
    });

    const claudeDocument = await readFile(path.join(workspaceDir, "CLAUDE.md"), "utf8");
    const agentsDocument = await readFile(path.join(workspaceDir, "AGENTS.md"), "utf8");

    expect(stripGeneratedMarker(claudeDocument)).toBe(stripGeneratedMarker(agentsDocument));
  });

  it("reports a three-adapter capability matrix with schema version 1", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "harness-capabilities-matrix-"));

    await withCwd(tempRoot, async () => {
      const capabilitiesIo = createIo();
      expect(await runCli(["adapters", "capabilities", "--json"], capabilitiesIo.io)).toBe(0);

      const report = adaptersCapabilitiesReportSchema.parse(JSON.parse(capabilitiesIo.stdout[0] ?? "{}"));
      expect(report.schema_version).toBe(1);
      expect(report.adapters).toEqual([
        {
          id: "claude-code",
          features: ["claude-agents-md", "claude-commands-md", "claude-docs", "claude-hooks", "claude-mcp", "claude-md", "claude-metrics", "claude-plugins", "claude-reference-projects", "claude-rules-md", "claude-scripts", "claude-skills"]
        },
        {
          id: "codex",
          features: ["agents-md", "codex-config-toml"]
        },
        {
          id: "cursor",
          features: ["cursor-mcp-json", "cursor-rules-mdc"]
        }
      ]);
    });
  });
});
