import { readFile } from "node:fs/promises";
import path from "node:path";

import { HarnessError } from "../errors.js";
import { GENERATED_AGENTS_HEADER } from "../constants.js";
import type { FullPlannedFile, PartialPlannedFile, PlannedContent, PlannedFile } from "../sync-types.js";

export function toPortablePath(value: string): string {
  return value.split(path.sep).join("/");
}

function ensureTrailingNewline(source: string): string {
  return source.endsWith("\n") ? source : `${source}\n`;
}

export function stripGeneratedHeader(source: string): string {
  if (!source.startsWith(GENERATED_AGENTS_HEADER)) {
    return source;
  }

  return source.slice(GENERATED_AGENTS_HEADER.length).replace(/^\r?\n\r?\n?/, "");
}

export function buildGeneratedInstructions(source: string): string {
  return `${GENERATED_AGENTS_HEADER}\n\n${stripGeneratedHeader(source)}`;
}

export function buildGeneratedMarkdown(source: string, sourcePath: string): string {
  const marker = `<!-- generated by harness; do not edit. Source: ${sourcePath} -->`;
  const frontmatterMatch = source.match(/^(---\r?\n[\s\S]*?\r?\n---)([\s\S]*)$/);

  if (!frontmatterMatch) {
    return ensureTrailingNewline(`${marker}\n${source}`);
  }

  const [, frontmatter, tail] = frontmatterMatch;
  return ensureTrailingNewline(`${frontmatter}\n${marker}${tail}`);
}

export function createPlannedFile(
  rootDir: string,
  targetRoot: string,
  relativePath: string,
  content: PlannedContent,
  mode = 0o644
): FullPlannedFile {
  const absolutePath = path.resolve(targetRoot, relativePath);

  return {
    rootDir,
    path: toPortablePath(path.relative(rootDir, absolutePath)),
    absolutePath,
    kind: "full",
    content,
    mode
  };
}

export function createPartialJsonPlannedFile(
  rootDir: string,
  targetRoot: string,
  relativePath: string,
  ownedValues: Readonly<Record<string, unknown>>,
  mode = 0o644
): PartialPlannedFile {
  const absolutePath = path.resolve(targetRoot, relativePath);
  const ownedKeys = [...new Set(Object.keys(ownedValues))].sort((left, right) => left.localeCompare(right));

  return {
    rootDir,
    path: toPortablePath(path.relative(rootDir, absolutePath)),
    absolutePath,
    kind: "partial-json",
    ownedKeys,
    ownedValues,
    mode
  };
}

export function isPartialJsonPlannedFile(file: PlannedFile): file is PartialPlannedFile {
  return file.kind === "partial-json";
}

export async function readTemplate(rootDir: string, filePath: string, adapterId: string): Promise<string> {
  const resolvedPath = path.resolve(rootDir, filePath);

  try {
    return await readFile(resolvedPath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      throw new HarnessError(`Adapter \`${adapterId}\` could not read template: ${filePath}`, "ADAPTER_TEMPLATE_MISSING");
    }

    throw error;
  }
}
